package com.iboray.lms.infrastructure.dao;

import com.iboray.lms.domain.entity.Billing;
import com.iboray.lms.domain.entity.BillingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BillingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    int countByExample(BillingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    int deleteByExample(BillingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    int insert(Billing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    int insertSelective(Billing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    List<Billing> selectByExample(BillingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    Billing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Billing record, @Param("example") BillingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Billing record, @Param("example") BillingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Billing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Billing record);
}