package com.iboray.lms.infrastructure.dao;

import com.iboray.lms.domain.entity.CGcontractCredit;
import com.iboray.lms.domain.entity.CGcontractCreditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CGcontractCreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    int countByExample(CGcontractCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    int deleteByExample(CGcontractCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    int insert(CGcontractCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    int insertSelective(CGcontractCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    List<CGcontractCredit> selectByExample(CGcontractCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    CGcontractCredit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CGcontractCredit record, @Param("example") CGcontractCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CGcontractCredit record, @Param("example") CGcontractCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CGcontractCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CGcontractCredit record);
}