package com.iboray.lms.infrastructure.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.iboray.lms.domain.entity.CGcontract;
import com.iboray.lms.domain.entity.CGcontractExample;

public interface CGcontractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontract
     *
     * @mbggenerated
     */
    int countByExample(CGcontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontract
     *
     * @mbggenerated
     */
    int deleteByExample(CGcontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontract
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontract
     *
     * @mbggenerated
     */
    int insert(CGcontract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontract
     *
     * @mbggenerated
     */
    int insertSelective(CGcontract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontract
     *
     * @mbggenerated
     */
    List<CGcontract> selectByExample(CGcontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontract
     *
     * @mbggenerated
     */
    CGcontract selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontract
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CGcontract record, @Param("example") CGcontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontract
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CGcontract record, @Param("example") CGcontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontract
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CGcontract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontract
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CGcontract record);
    
    CGcontract selectByNo(String no);
    
    String selectMaxNo();
}