package com.iboray.lms.infrastructure.dao;

import com.iboray.lms.domain.entity.Payed;
import com.iboray.lms.domain.entity.PayedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    int countByExample(PayedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    int deleteByExample(PayedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    int insert(Payed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    int insertSelective(Payed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    List<Payed> selectByExample(PayedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    Payed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Payed record, @Param("example") PayedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Payed record, @Param("example") PayedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Payed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Payed record);
}