package com.iboray.lms.infrastructure.dao;

import com.iboray.lms.domain.entity.Planchangedetails;
import com.iboray.lms.domain.entity.PlanchangedetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlanchangedetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_planchangedetails
     *
     * @mbggenerated
     */
    int countByExample(PlanchangedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_planchangedetails
     *
     * @mbggenerated
     */
    int deleteByExample(PlanchangedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_planchangedetails
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_planchangedetails
     *
     * @mbggenerated
     */
    int insert(Planchangedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_planchangedetails
     *
     * @mbggenerated
     */
    int insertSelective(Planchangedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_planchangedetails
     *
     * @mbggenerated
     */
    List<Planchangedetails> selectByExample(PlanchangedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_planchangedetails
     *
     * @mbggenerated
     */
    Planchangedetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_planchangedetails
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Planchangedetails record, @Param("example") PlanchangedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_planchangedetails
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Planchangedetails record, @Param("example") PlanchangedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_planchangedetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Planchangedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_planchangedetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Planchangedetails record);
}