package com.iboray.lms.infrastructure.dao;

import com.iboray.lms.domain.entity.Suppliers;
import com.iboray.lms.domain.entity.SuppliersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SuppliersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_suppliers
     *
     * @mbggenerated
     */
    int countByExample(SuppliersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_suppliers
     *
     * @mbggenerated
     */
    int deleteByExample(SuppliersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_suppliers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_suppliers
     *
     * @mbggenerated
     */
    int insert(Suppliers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_suppliers
     *
     * @mbggenerated
     */
    int insertSelective(Suppliers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_suppliers
     *
     * @mbggenerated
     */
    List<Suppliers> selectByExample(SuppliersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_suppliers
     *
     * @mbggenerated
     */
    Suppliers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_suppliers
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Suppliers record, @Param("example") SuppliersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_suppliers
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Suppliers record, @Param("example") SuppliersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_suppliers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Suppliers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_suppliers
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Suppliers record);
}