package com.iboray.lms.infrastructure.dao;

import com.iboray.lms.domain.entity.Usecomp;
import com.iboray.lms.domain.entity.UsecompExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UsecompMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_usecomp
     *
     * @mbggenerated
     */
    int countByExample(UsecompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_usecomp
     *
     * @mbggenerated
     */
    int deleteByExample(UsecompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_usecomp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_usecomp
     *
     * @mbggenerated
     */
    int insert(Usecomp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_usecomp
     *
     * @mbggenerated
     */
    int insertSelective(Usecomp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_usecomp
     *
     * @mbggenerated
     */
    List<Usecomp> selectByExample(UsecompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_usecomp
     *
     * @mbggenerated
     */
    Usecomp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_usecomp
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Usecomp record, @Param("example") UsecompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_usecomp
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Usecomp record, @Param("example") UsecompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_usecomp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Usecomp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_c_usecomp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Usecomp record);
    
    Usecomp selectByNo(String no);
}