package com.iboray.lms.infrastructure.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.iboray.lms.domain.entity.Xscontract;
import com.iboray.lms.domain.entity.XscontractExample;

public interface XscontractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_xscontract
     *
     * @mbggenerated
     */
    int countByExample(XscontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_xscontract
     *
     * @mbggenerated
     */
    int deleteByExample(XscontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_xscontract
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_xscontract
     *
     * @mbggenerated
     */
    int insert(Xscontract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_xscontract
     *
     * @mbggenerated
     */
    int insertSelective(Xscontract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_xscontract
     *
     * @mbggenerated
     */
    List<Xscontract> selectByExample(XscontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_xscontract
     *
     * @mbggenerated
     */
    Xscontract selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_xscontract
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Xscontract record, @Param("example") XscontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_xscontract
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Xscontract record, @Param("example") XscontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_xscontract
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Xscontract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_xscontract
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Xscontract record);
    
    Xscontract selectByNo(String no);

	String selectMaxNo();
}