package com.iboray.lms.domain.entity;

import java.util.ArrayList;
import java.util.List;

public class ArrivalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    public ArrivalExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andArrivalnoIsNull() {
            addCriterion("arrivalNo is null");
            return (Criteria) this;
        }

        public Criteria andArrivalnoIsNotNull() {
            addCriterion("arrivalNo is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalnoEqualTo(String value) {
            addCriterion("arrivalNo =", value, "arrivalno");
            return (Criteria) this;
        }

        public Criteria andArrivalnoNotEqualTo(String value) {
            addCriterion("arrivalNo <>", value, "arrivalno");
            return (Criteria) this;
        }

        public Criteria andArrivalnoGreaterThan(String value) {
            addCriterion("arrivalNo >", value, "arrivalno");
            return (Criteria) this;
        }

        public Criteria andArrivalnoGreaterThanOrEqualTo(String value) {
            addCriterion("arrivalNo >=", value, "arrivalno");
            return (Criteria) this;
        }

        public Criteria andArrivalnoLessThan(String value) {
            addCriterion("arrivalNo <", value, "arrivalno");
            return (Criteria) this;
        }

        public Criteria andArrivalnoLessThanOrEqualTo(String value) {
            addCriterion("arrivalNo <=", value, "arrivalno");
            return (Criteria) this;
        }

        public Criteria andArrivalnoLike(String value) {
            addCriterion("arrivalNo like", value, "arrivalno");
            return (Criteria) this;
        }

        public Criteria andArrivalnoNotLike(String value) {
            addCriterion("arrivalNo not like", value, "arrivalno");
            return (Criteria) this;
        }

        public Criteria andArrivalnoIn(List<String> values) {
            addCriterion("arrivalNo in", values, "arrivalno");
            return (Criteria) this;
        }

        public Criteria andArrivalnoNotIn(List<String> values) {
            addCriterion("arrivalNo not in", values, "arrivalno");
            return (Criteria) this;
        }

        public Criteria andArrivalnoBetween(String value1, String value2) {
            addCriterion("arrivalNo between", value1, value2, "arrivalno");
            return (Criteria) this;
        }

        public Criteria andArrivalnoNotBetween(String value1, String value2) {
            addCriterion("arrivalNo not between", value1, value2, "arrivalno");
            return (Criteria) this;
        }

        public Criteria andArrivalnumberIsNull() {
            addCriterion("arrivalNumber is null");
            return (Criteria) this;
        }

        public Criteria andArrivalnumberIsNotNull() {
            addCriterion("arrivalNumber is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalnumberEqualTo(Double value) {
            addCriterion("arrivalNumber =", value, "arrivalnumber");
            return (Criteria) this;
        }

        public Criteria andArrivalnumberNotEqualTo(Double value) {
            addCriterion("arrivalNumber <>", value, "arrivalnumber");
            return (Criteria) this;
        }

        public Criteria andArrivalnumberGreaterThan(Double value) {
            addCriterion("arrivalNumber >", value, "arrivalnumber");
            return (Criteria) this;
        }

        public Criteria andArrivalnumberGreaterThanOrEqualTo(Double value) {
            addCriterion("arrivalNumber >=", value, "arrivalnumber");
            return (Criteria) this;
        }

        public Criteria andArrivalnumberLessThan(Double value) {
            addCriterion("arrivalNumber <", value, "arrivalnumber");
            return (Criteria) this;
        }

        public Criteria andArrivalnumberLessThanOrEqualTo(Double value) {
            addCriterion("arrivalNumber <=", value, "arrivalnumber");
            return (Criteria) this;
        }

        public Criteria andArrivalnumberIn(List<Double> values) {
            addCriterion("arrivalNumber in", values, "arrivalnumber");
            return (Criteria) this;
        }

        public Criteria andArrivalnumberNotIn(List<Double> values) {
            addCriterion("arrivalNumber not in", values, "arrivalnumber");
            return (Criteria) this;
        }

        public Criteria andArrivalnumberBetween(Double value1, Double value2) {
            addCriterion("arrivalNumber between", value1, value2, "arrivalnumber");
            return (Criteria) this;
        }

        public Criteria andArrivalnumberNotBetween(Double value1, Double value2) {
            addCriterion("arrivalNumber not between", value1, value2, "arrivalnumber");
            return (Criteria) this;
        }

        public Criteria andArrivaldateIsNull() {
            addCriterion("arrivalDate is null");
            return (Criteria) this;
        }

        public Criteria andArrivaldateIsNotNull() {
            addCriterion("arrivalDate is not null");
            return (Criteria) this;
        }

        public Criteria andArrivaldateEqualTo(String value) {
            addCriterion("arrivalDate =", value, "arrivaldate");
            return (Criteria) this;
        }

        public Criteria andArrivaldateNotEqualTo(String value) {
            addCriterion("arrivalDate <>", value, "arrivaldate");
            return (Criteria) this;
        }

        public Criteria andArrivaldateGreaterThan(String value) {
            addCriterion("arrivalDate >", value, "arrivaldate");
            return (Criteria) this;
        }

        public Criteria andArrivaldateGreaterThanOrEqualTo(String value) {
            addCriterion("arrivalDate >=", value, "arrivaldate");
            return (Criteria) this;
        }

        public Criteria andArrivaldateLessThan(String value) {
            addCriterion("arrivalDate <", value, "arrivaldate");
            return (Criteria) this;
        }

        public Criteria andArrivaldateLessThanOrEqualTo(String value) {
            addCriterion("arrivalDate <=", value, "arrivaldate");
            return (Criteria) this;
        }

        public Criteria andArrivaldateLike(String value) {
            addCriterion("arrivalDate like", value, "arrivaldate");
            return (Criteria) this;
        }

        public Criteria andArrivaldateNotLike(String value) {
            addCriterion("arrivalDate not like", value, "arrivaldate");
            return (Criteria) this;
        }

        public Criteria andArrivaldateIn(List<String> values) {
            addCriterion("arrivalDate in", values, "arrivaldate");
            return (Criteria) this;
        }

        public Criteria andArrivaldateNotIn(List<String> values) {
            addCriterion("arrivalDate not in", values, "arrivaldate");
            return (Criteria) this;
        }

        public Criteria andArrivaldateBetween(String value1, String value2) {
            addCriterion("arrivalDate between", value1, value2, "arrivaldate");
            return (Criteria) this;
        }

        public Criteria andArrivaldateNotBetween(String value1, String value2) {
            addCriterion("arrivalDate not between", value1, value2, "arrivaldate");
            return (Criteria) this;
        }

        public Criteria andFkPlannoIsNull() {
            addCriterion("FK_planNo is null");
            return (Criteria) this;
        }

        public Criteria andFkPlannoIsNotNull() {
            addCriterion("FK_planNo is not null");
            return (Criteria) this;
        }

        public Criteria andFkPlannoEqualTo(String value) {
            addCriterion("FK_planNo =", value, "fkPlanno");
            return (Criteria) this;
        }

        public Criteria andFkPlannoNotEqualTo(String value) {
            addCriterion("FK_planNo <>", value, "fkPlanno");
            return (Criteria) this;
        }

        public Criteria andFkPlannoGreaterThan(String value) {
            addCriterion("FK_planNo >", value, "fkPlanno");
            return (Criteria) this;
        }

        public Criteria andFkPlannoGreaterThanOrEqualTo(String value) {
            addCriterion("FK_planNo >=", value, "fkPlanno");
            return (Criteria) this;
        }

        public Criteria andFkPlannoLessThan(String value) {
            addCriterion("FK_planNo <", value, "fkPlanno");
            return (Criteria) this;
        }

        public Criteria andFkPlannoLessThanOrEqualTo(String value) {
            addCriterion("FK_planNo <=", value, "fkPlanno");
            return (Criteria) this;
        }

        public Criteria andFkPlannoLike(String value) {
            addCriterion("FK_planNo like", value, "fkPlanno");
            return (Criteria) this;
        }

        public Criteria andFkPlannoNotLike(String value) {
            addCriterion("FK_planNo not like", value, "fkPlanno");
            return (Criteria) this;
        }

        public Criteria andFkPlannoIn(List<String> values) {
            addCriterion("FK_planNo in", values, "fkPlanno");
            return (Criteria) this;
        }

        public Criteria andFkPlannoNotIn(List<String> values) {
            addCriterion("FK_planNo not in", values, "fkPlanno");
            return (Criteria) this;
        }

        public Criteria andFkPlannoBetween(String value1, String value2) {
            addCriterion("FK_planNo between", value1, value2, "fkPlanno");
            return (Criteria) this;
        }

        public Criteria andFkPlannoNotBetween(String value1, String value2) {
            addCriterion("FK_planNo not between", value1, value2, "fkPlanno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoIsNull() {
            addCriterion("FK_cgContractNo is null");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoIsNotNull() {
            addCriterion("FK_cgContractNo is not null");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoEqualTo(String value) {
            addCriterion("FK_cgContractNo =", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoNotEqualTo(String value) {
            addCriterion("FK_cgContractNo <>", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoGreaterThan(String value) {
            addCriterion("FK_cgContractNo >", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoGreaterThanOrEqualTo(String value) {
            addCriterion("FK_cgContractNo >=", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoLessThan(String value) {
            addCriterion("FK_cgContractNo <", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoLessThanOrEqualTo(String value) {
            addCriterion("FK_cgContractNo <=", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoLike(String value) {
            addCriterion("FK_cgContractNo like", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoNotLike(String value) {
            addCriterion("FK_cgContractNo not like", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoIn(List<String> values) {
            addCriterion("FK_cgContractNo in", values, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoNotIn(List<String> values) {
            addCriterion("FK_cgContractNo not in", values, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoBetween(String value1, String value2) {
            addCriterion("FK_cgContractNo between", value1, value2, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoNotBetween(String value1, String value2) {
            addCriterion("FK_cgContractNo not between", value1, value2, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIsNull() {
            addCriterion("FK_userNo is null");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIsNotNull() {
            addCriterion("FK_userNo is not null");
            return (Criteria) this;
        }

        public Criteria andFkUsernoEqualTo(String value) {
            addCriterion("FK_userNo =", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotEqualTo(String value) {
            addCriterion("FK_userNo <>", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoGreaterThan(String value) {
            addCriterion("FK_userNo >", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoGreaterThanOrEqualTo(String value) {
            addCriterion("FK_userNo >=", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLessThan(String value) {
            addCriterion("FK_userNo <", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLessThanOrEqualTo(String value) {
            addCriterion("FK_userNo <=", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLike(String value) {
            addCriterion("FK_userNo like", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotLike(String value) {
            addCriterion("FK_userNo not like", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIn(List<String> values) {
            addCriterion("FK_userNo in", values, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotIn(List<String> values) {
            addCriterion("FK_userNo not in", values, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoBetween(String value1, String value2) {
            addCriterion("FK_userNo between", value1, value2, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotBetween(String value1, String value2) {
            addCriterion("FK_userNo not between", value1, value2, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNull() {
            addCriterion("invalid is null");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNotNull() {
            addCriterion("invalid is not null");
            return (Criteria) this;
        }

        public Criteria andInvalidEqualTo(String value) {
            addCriterion("invalid =", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotEqualTo(String value) {
            addCriterion("invalid <>", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThan(String value) {
            addCriterion("invalid >", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThanOrEqualTo(String value) {
            addCriterion("invalid >=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThan(String value) {
            addCriterion("invalid <", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThanOrEqualTo(String value) {
            addCriterion("invalid <=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLike(String value) {
            addCriterion("invalid like", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotLike(String value) {
            addCriterion("invalid not like", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidIn(List<String> values) {
            addCriterion("invalid in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotIn(List<String> values) {
            addCriterion("invalid not in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidBetween(String value1, String value2) {
            addCriterion("invalid between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotBetween(String value1, String value2) {
            addCriterion("invalid not between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("createTime like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("createTime not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(String value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(String value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(String value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(String value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(String value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLike(String value) {
            addCriterion("updateTime like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotLike(String value) {
            addCriterion("updateTime not like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<String> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<String> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(String value1, String value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(String value1, String value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_arrival
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_arrival
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}