package com.iboray.lms.domain.entity;

public class Arrival {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_arrival.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_arrival.arrivalNo
     *
     * @mbggenerated
     */
    private String arrivalno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_arrival.arrivalNumber
     *
     * @mbggenerated
     */
    private Double arrivalnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_arrival.arrivalDate
     *
     * @mbggenerated
     */
    private String arrivaldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_arrival.FK_planNo
     *
     * @mbggenerated
     */
    private String fkPlanno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_arrival.FK_cgContractNo
     *
     * @mbggenerated
     */
    private String fkCgcontractno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_arrival.FK_userNo
     *
     * @mbggenerated
     */
    private String fkUserno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_arrival.invalid
     *
     * @mbggenerated
     */
    private String invalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_arrival.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_arrival.updateTime
     *
     * @mbggenerated
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_arrival.id
     *
     * @return the value of lm_d_arrival.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_arrival.id
     *
     * @param id the value for lm_d_arrival.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_arrival.arrivalNo
     *
     * @return the value of lm_d_arrival.arrivalNo
     *
     * @mbggenerated
     */
    public String getArrivalno() {
        return arrivalno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_arrival.arrivalNo
     *
     * @param arrivalno the value for lm_d_arrival.arrivalNo
     *
     * @mbggenerated
     */
    public void setArrivalno(String arrivalno) {
        this.arrivalno = arrivalno == null ? null : arrivalno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_arrival.arrivalNumber
     *
     * @return the value of lm_d_arrival.arrivalNumber
     *
     * @mbggenerated
     */
    public Double getArrivalnumber() {
        return arrivalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_arrival.arrivalNumber
     *
     * @param arrivalnumber the value for lm_d_arrival.arrivalNumber
     *
     * @mbggenerated
     */
    public void setArrivalnumber(Double arrivalnumber) {
        this.arrivalnumber = arrivalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_arrival.arrivalDate
     *
     * @return the value of lm_d_arrival.arrivalDate
     *
     * @mbggenerated
     */
    public String getArrivaldate() {
        return arrivaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_arrival.arrivalDate
     *
     * @param arrivaldate the value for lm_d_arrival.arrivalDate
     *
     * @mbggenerated
     */
    public void setArrivaldate(String arrivaldate) {
        this.arrivaldate = arrivaldate == null ? null : arrivaldate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_arrival.FK_planNo
     *
     * @return the value of lm_d_arrival.FK_planNo
     *
     * @mbggenerated
     */
    public String getFkPlanno() {
        return fkPlanno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_arrival.FK_planNo
     *
     * @param fkPlanno the value for lm_d_arrival.FK_planNo
     *
     * @mbggenerated
     */
    public void setFkPlanno(String fkPlanno) {
        this.fkPlanno = fkPlanno == null ? null : fkPlanno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_arrival.FK_cgContractNo
     *
     * @return the value of lm_d_arrival.FK_cgContractNo
     *
     * @mbggenerated
     */
    public String getFkCgcontractno() {
        return fkCgcontractno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_arrival.FK_cgContractNo
     *
     * @param fkCgcontractno the value for lm_d_arrival.FK_cgContractNo
     *
     * @mbggenerated
     */
    public void setFkCgcontractno(String fkCgcontractno) {
        this.fkCgcontractno = fkCgcontractno == null ? null : fkCgcontractno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_arrival.FK_userNo
     *
     * @return the value of lm_d_arrival.FK_userNo
     *
     * @mbggenerated
     */
    public String getFkUserno() {
        return fkUserno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_arrival.FK_userNo
     *
     * @param fkUserno the value for lm_d_arrival.FK_userNo
     *
     * @mbggenerated
     */
    public void setFkUserno(String fkUserno) {
        this.fkUserno = fkUserno == null ? null : fkUserno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_arrival.invalid
     *
     * @return the value of lm_d_arrival.invalid
     *
     * @mbggenerated
     */
    public String getInvalid() {
        return invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_arrival.invalid
     *
     * @param invalid the value for lm_d_arrival.invalid
     *
     * @mbggenerated
     */
    public void setInvalid(String invalid) {
        this.invalid = invalid == null ? null : invalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_arrival.createTime
     *
     * @return the value of lm_d_arrival.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_arrival.createTime
     *
     * @param createtime the value for lm_d_arrival.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_arrival.updateTime
     *
     * @return the value of lm_d_arrival.updateTime
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_arrival.updateTime
     *
     * @param updatetime the value for lm_d_arrival.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }
}