package com.iboray.lms.domain.entity;

import java.util.ArrayList;
import java.util.List;

public class BillingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    public BillingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBillingnoIsNull() {
            addCriterion("billingNo is null");
            return (Criteria) this;
        }

        public Criteria andBillingnoIsNotNull() {
            addCriterion("billingNo is not null");
            return (Criteria) this;
        }

        public Criteria andBillingnoEqualTo(String value) {
            addCriterion("billingNo =", value, "billingno");
            return (Criteria) this;
        }

        public Criteria andBillingnoNotEqualTo(String value) {
            addCriterion("billingNo <>", value, "billingno");
            return (Criteria) this;
        }

        public Criteria andBillingnoGreaterThan(String value) {
            addCriterion("billingNo >", value, "billingno");
            return (Criteria) this;
        }

        public Criteria andBillingnoGreaterThanOrEqualTo(String value) {
            addCriterion("billingNo >=", value, "billingno");
            return (Criteria) this;
        }

        public Criteria andBillingnoLessThan(String value) {
            addCriterion("billingNo <", value, "billingno");
            return (Criteria) this;
        }

        public Criteria andBillingnoLessThanOrEqualTo(String value) {
            addCriterion("billingNo <=", value, "billingno");
            return (Criteria) this;
        }

        public Criteria andBillingnoLike(String value) {
            addCriterion("billingNo like", value, "billingno");
            return (Criteria) this;
        }

        public Criteria andBillingnoNotLike(String value) {
            addCriterion("billingNo not like", value, "billingno");
            return (Criteria) this;
        }

        public Criteria andBillingnoIn(List<String> values) {
            addCriterion("billingNo in", values, "billingno");
            return (Criteria) this;
        }

        public Criteria andBillingnoNotIn(List<String> values) {
            addCriterion("billingNo not in", values, "billingno");
            return (Criteria) this;
        }

        public Criteria andBillingnoBetween(String value1, String value2) {
            addCriterion("billingNo between", value1, value2, "billingno");
            return (Criteria) this;
        }

        public Criteria andBillingnoNotBetween(String value1, String value2) {
            addCriterion("billingNo not between", value1, value2, "billingno");
            return (Criteria) this;
        }

        public Criteria andBillingmoneyIsNull() {
            addCriterion("billingMoney is null");
            return (Criteria) this;
        }

        public Criteria andBillingmoneyIsNotNull() {
            addCriterion("billingMoney is not null");
            return (Criteria) this;
        }

        public Criteria andBillingmoneyEqualTo(Double value) {
            addCriterion("billingMoney =", value, "billingmoney");
            return (Criteria) this;
        }

        public Criteria andBillingmoneyNotEqualTo(Double value) {
            addCriterion("billingMoney <>", value, "billingmoney");
            return (Criteria) this;
        }

        public Criteria andBillingmoneyGreaterThan(Double value) {
            addCriterion("billingMoney >", value, "billingmoney");
            return (Criteria) this;
        }

        public Criteria andBillingmoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("billingMoney >=", value, "billingmoney");
            return (Criteria) this;
        }

        public Criteria andBillingmoneyLessThan(Double value) {
            addCriterion("billingMoney <", value, "billingmoney");
            return (Criteria) this;
        }

        public Criteria andBillingmoneyLessThanOrEqualTo(Double value) {
            addCriterion("billingMoney <=", value, "billingmoney");
            return (Criteria) this;
        }

        public Criteria andBillingmoneyIn(List<Double> values) {
            addCriterion("billingMoney in", values, "billingmoney");
            return (Criteria) this;
        }

        public Criteria andBillingmoneyNotIn(List<Double> values) {
            addCriterion("billingMoney not in", values, "billingmoney");
            return (Criteria) this;
        }

        public Criteria andBillingmoneyBetween(Double value1, Double value2) {
            addCriterion("billingMoney between", value1, value2, "billingmoney");
            return (Criteria) this;
        }

        public Criteria andBillingmoneyNotBetween(Double value1, Double value2) {
            addCriterion("billingMoney not between", value1, value2, "billingmoney");
            return (Criteria) this;
        }

        public Criteria andBillingdateIsNull() {
            addCriterion("billingDate is null");
            return (Criteria) this;
        }

        public Criteria andBillingdateIsNotNull() {
            addCriterion("billingDate is not null");
            return (Criteria) this;
        }

        public Criteria andBillingdateEqualTo(String value) {
            addCriterion("billingDate =", value, "billingdate");
            return (Criteria) this;
        }

        public Criteria andBillingdateNotEqualTo(String value) {
            addCriterion("billingDate <>", value, "billingdate");
            return (Criteria) this;
        }

        public Criteria andBillingdateGreaterThan(String value) {
            addCriterion("billingDate >", value, "billingdate");
            return (Criteria) this;
        }

        public Criteria andBillingdateGreaterThanOrEqualTo(String value) {
            addCriterion("billingDate >=", value, "billingdate");
            return (Criteria) this;
        }

        public Criteria andBillingdateLessThan(String value) {
            addCriterion("billingDate <", value, "billingdate");
            return (Criteria) this;
        }

        public Criteria andBillingdateLessThanOrEqualTo(String value) {
            addCriterion("billingDate <=", value, "billingdate");
            return (Criteria) this;
        }

        public Criteria andBillingdateLike(String value) {
            addCriterion("billingDate like", value, "billingdate");
            return (Criteria) this;
        }

        public Criteria andBillingdateNotLike(String value) {
            addCriterion("billingDate not like", value, "billingdate");
            return (Criteria) this;
        }

        public Criteria andBillingdateIn(List<String> values) {
            addCriterion("billingDate in", values, "billingdate");
            return (Criteria) this;
        }

        public Criteria andBillingdateNotIn(List<String> values) {
            addCriterion("billingDate not in", values, "billingdate");
            return (Criteria) this;
        }

        public Criteria andBillingdateBetween(String value1, String value2) {
            addCriterion("billingDate between", value1, value2, "billingdate");
            return (Criteria) this;
        }

        public Criteria andBillingdateNotBetween(String value1, String value2) {
            addCriterion("billingDate not between", value1, value2, "billingdate");
            return (Criteria) this;
        }

        public Criteria andBillingnumberIsNull() {
            addCriterion("billingNumber is null");
            return (Criteria) this;
        }

        public Criteria andBillingnumberIsNotNull() {
            addCriterion("billingNumber is not null");
            return (Criteria) this;
        }

        public Criteria andBillingnumberEqualTo(Double value) {
            addCriterion("billingNumber =", value, "billingnumber");
            return (Criteria) this;
        }

        public Criteria andBillingnumberNotEqualTo(Double value) {
            addCriterion("billingNumber <>", value, "billingnumber");
            return (Criteria) this;
        }

        public Criteria andBillingnumberGreaterThan(Double value) {
            addCriterion("billingNumber >", value, "billingnumber");
            return (Criteria) this;
        }

        public Criteria andBillingnumberGreaterThanOrEqualTo(Double value) {
            addCriterion("billingNumber >=", value, "billingnumber");
            return (Criteria) this;
        }

        public Criteria andBillingnumberLessThan(Double value) {
            addCriterion("billingNumber <", value, "billingnumber");
            return (Criteria) this;
        }

        public Criteria andBillingnumberLessThanOrEqualTo(Double value) {
            addCriterion("billingNumber <=", value, "billingnumber");
            return (Criteria) this;
        }

        public Criteria andBillingnumberIn(List<Double> values) {
            addCriterion("billingNumber in", values, "billingnumber");
            return (Criteria) this;
        }

        public Criteria andBillingnumberNotIn(List<Double> values) {
            addCriterion("billingNumber not in", values, "billingnumber");
            return (Criteria) this;
        }

        public Criteria andBillingnumberBetween(Double value1, Double value2) {
            addCriterion("billingNumber between", value1, value2, "billingnumber");
            return (Criteria) this;
        }

        public Criteria andBillingnumberNotBetween(Double value1, Double value2) {
            addCriterion("billingNumber not between", value1, value2, "billingnumber");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoIsNull() {
            addCriterion("FK_xsContractNo is null");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoIsNotNull() {
            addCriterion("FK_xsContractNo is not null");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoEqualTo(String value) {
            addCriterion("FK_xsContractNo =", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoNotEqualTo(String value) {
            addCriterion("FK_xsContractNo <>", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoGreaterThan(String value) {
            addCriterion("FK_xsContractNo >", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoGreaterThanOrEqualTo(String value) {
            addCriterion("FK_xsContractNo >=", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoLessThan(String value) {
            addCriterion("FK_xsContractNo <", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoLessThanOrEqualTo(String value) {
            addCriterion("FK_xsContractNo <=", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoLike(String value) {
            addCriterion("FK_xsContractNo like", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoNotLike(String value) {
            addCriterion("FK_xsContractNo not like", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoIn(List<String> values) {
            addCriterion("FK_xsContractNo in", values, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoNotIn(List<String> values) {
            addCriterion("FK_xsContractNo not in", values, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoBetween(String value1, String value2) {
            addCriterion("FK_xsContractNo between", value1, value2, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoNotBetween(String value1, String value2) {
            addCriterion("FK_xsContractNo not between", value1, value2, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkArrivalnoIsNull() {
            addCriterion("FK_arrivalNo is null");
            return (Criteria) this;
        }

        public Criteria andFkArrivalnoIsNotNull() {
            addCriterion("FK_arrivalNo is not null");
            return (Criteria) this;
        }

        public Criteria andFkArrivalnoEqualTo(String value) {
            addCriterion("FK_arrivalNo =", value, "fkArrivalno");
            return (Criteria) this;
        }

        public Criteria andFkArrivalnoNotEqualTo(String value) {
            addCriterion("FK_arrivalNo <>", value, "fkArrivalno");
            return (Criteria) this;
        }

        public Criteria andFkArrivalnoGreaterThan(String value) {
            addCriterion("FK_arrivalNo >", value, "fkArrivalno");
            return (Criteria) this;
        }

        public Criteria andFkArrivalnoGreaterThanOrEqualTo(String value) {
            addCriterion("FK_arrivalNo >=", value, "fkArrivalno");
            return (Criteria) this;
        }

        public Criteria andFkArrivalnoLessThan(String value) {
            addCriterion("FK_arrivalNo <", value, "fkArrivalno");
            return (Criteria) this;
        }

        public Criteria andFkArrivalnoLessThanOrEqualTo(String value) {
            addCriterion("FK_arrivalNo <=", value, "fkArrivalno");
            return (Criteria) this;
        }

        public Criteria andFkArrivalnoLike(String value) {
            addCriterion("FK_arrivalNo like", value, "fkArrivalno");
            return (Criteria) this;
        }

        public Criteria andFkArrivalnoNotLike(String value) {
            addCriterion("FK_arrivalNo not like", value, "fkArrivalno");
            return (Criteria) this;
        }

        public Criteria andFkArrivalnoIn(List<String> values) {
            addCriterion("FK_arrivalNo in", values, "fkArrivalno");
            return (Criteria) this;
        }

        public Criteria andFkArrivalnoNotIn(List<String> values) {
            addCriterion("FK_arrivalNo not in", values, "fkArrivalno");
            return (Criteria) this;
        }

        public Criteria andFkArrivalnoBetween(String value1, String value2) {
            addCriterion("FK_arrivalNo between", value1, value2, "fkArrivalno");
            return (Criteria) this;
        }

        public Criteria andFkArrivalnoNotBetween(String value1, String value2) {
            addCriterion("FK_arrivalNo not between", value1, value2, "fkArrivalno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIsNull() {
            addCriterion("FK_userNo is null");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIsNotNull() {
            addCriterion("FK_userNo is not null");
            return (Criteria) this;
        }

        public Criteria andFkUsernoEqualTo(String value) {
            addCriterion("FK_userNo =", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotEqualTo(String value) {
            addCriterion("FK_userNo <>", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoGreaterThan(String value) {
            addCriterion("FK_userNo >", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoGreaterThanOrEqualTo(String value) {
            addCriterion("FK_userNo >=", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLessThan(String value) {
            addCriterion("FK_userNo <", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLessThanOrEqualTo(String value) {
            addCriterion("FK_userNo <=", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLike(String value) {
            addCriterion("FK_userNo like", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotLike(String value) {
            addCriterion("FK_userNo not like", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIn(List<String> values) {
            addCriterion("FK_userNo in", values, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotIn(List<String> values) {
            addCriterion("FK_userNo not in", values, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoBetween(String value1, String value2) {
            addCriterion("FK_userNo between", value1, value2, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotBetween(String value1, String value2) {
            addCriterion("FK_userNo not between", value1, value2, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNull() {
            addCriterion("invalid is null");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNotNull() {
            addCriterion("invalid is not null");
            return (Criteria) this;
        }

        public Criteria andInvalidEqualTo(String value) {
            addCriterion("invalid =", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotEqualTo(String value) {
            addCriterion("invalid <>", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThan(String value) {
            addCriterion("invalid >", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThanOrEqualTo(String value) {
            addCriterion("invalid >=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThan(String value) {
            addCriterion("invalid <", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThanOrEqualTo(String value) {
            addCriterion("invalid <=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLike(String value) {
            addCriterion("invalid like", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotLike(String value) {
            addCriterion("invalid not like", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidIn(List<String> values) {
            addCriterion("invalid in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotIn(List<String> values) {
            addCriterion("invalid not in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidBetween(String value1, String value2) {
            addCriterion("invalid between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotBetween(String value1, String value2) {
            addCriterion("invalid not between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("createTime like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("createTime not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(String value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(String value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(String value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(String value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(String value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLike(String value) {
            addCriterion("updateTime like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotLike(String value) {
            addCriterion("updateTime not like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<String> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<String> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(String value1, String value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(String value1, String value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_billing
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_billing
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}