package com.iboray.lms.domain.entity;

import java.util.ArrayList;
import java.util.List;

public class CGcontractCreditExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    public CGcontractCreditExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreditnoIsNull() {
            addCriterion("creditNo is null");
            return (Criteria) this;
        }

        public Criteria andCreditnoIsNotNull() {
            addCriterion("creditNo is not null");
            return (Criteria) this;
        }

        public Criteria andCreditnoEqualTo(String value) {
            addCriterion("creditNo =", value, "creditno");
            return (Criteria) this;
        }

        public Criteria andCreditnoNotEqualTo(String value) {
            addCriterion("creditNo <>", value, "creditno");
            return (Criteria) this;
        }

        public Criteria andCreditnoGreaterThan(String value) {
            addCriterion("creditNo >", value, "creditno");
            return (Criteria) this;
        }

        public Criteria andCreditnoGreaterThanOrEqualTo(String value) {
            addCriterion("creditNo >=", value, "creditno");
            return (Criteria) this;
        }

        public Criteria andCreditnoLessThan(String value) {
            addCriterion("creditNo <", value, "creditno");
            return (Criteria) this;
        }

        public Criteria andCreditnoLessThanOrEqualTo(String value) {
            addCriterion("creditNo <=", value, "creditno");
            return (Criteria) this;
        }

        public Criteria andCreditnoLike(String value) {
            addCriterion("creditNo like", value, "creditno");
            return (Criteria) this;
        }

        public Criteria andCreditnoNotLike(String value) {
            addCriterion("creditNo not like", value, "creditno");
            return (Criteria) this;
        }

        public Criteria andCreditnoIn(List<String> values) {
            addCriterion("creditNo in", values, "creditno");
            return (Criteria) this;
        }

        public Criteria andCreditnoNotIn(List<String> values) {
            addCriterion("creditNo not in", values, "creditno");
            return (Criteria) this;
        }

        public Criteria andCreditnoBetween(String value1, String value2) {
            addCriterion("creditNo between", value1, value2, "creditno");
            return (Criteria) this;
        }

        public Criteria andCreditnoNotBetween(String value1, String value2) {
            addCriterion("creditNo not between", value1, value2, "creditno");
            return (Criteria) this;
        }

        public Criteria andCreditmoneyIsNull() {
            addCriterion("creditMoney is null");
            return (Criteria) this;
        }

        public Criteria andCreditmoneyIsNotNull() {
            addCriterion("creditMoney is not null");
            return (Criteria) this;
        }

        public Criteria andCreditmoneyEqualTo(Double value) {
            addCriterion("creditMoney =", value, "creditmoney");
            return (Criteria) this;
        }

        public Criteria andCreditmoneyNotEqualTo(Double value) {
            addCriterion("creditMoney <>", value, "creditmoney");
            return (Criteria) this;
        }

        public Criteria andCreditmoneyGreaterThan(Double value) {
            addCriterion("creditMoney >", value, "creditmoney");
            return (Criteria) this;
        }

        public Criteria andCreditmoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("creditMoney >=", value, "creditmoney");
            return (Criteria) this;
        }

        public Criteria andCreditmoneyLessThan(Double value) {
            addCriterion("creditMoney <", value, "creditmoney");
            return (Criteria) this;
        }

        public Criteria andCreditmoneyLessThanOrEqualTo(Double value) {
            addCriterion("creditMoney <=", value, "creditmoney");
            return (Criteria) this;
        }

        public Criteria andCreditmoneyIn(List<Double> values) {
            addCriterion("creditMoney in", values, "creditmoney");
            return (Criteria) this;
        }

        public Criteria andCreditmoneyNotIn(List<Double> values) {
            addCriterion("creditMoney not in", values, "creditmoney");
            return (Criteria) this;
        }

        public Criteria andCreditmoneyBetween(Double value1, Double value2) {
            addCriterion("creditMoney between", value1, value2, "creditmoney");
            return (Criteria) this;
        }

        public Criteria andCreditmoneyNotBetween(Double value1, Double value2) {
            addCriterion("creditMoney not between", value1, value2, "creditmoney");
            return (Criteria) this;
        }

        public Criteria andCreditdateIsNull() {
            addCriterion("creditDate is null");
            return (Criteria) this;
        }

        public Criteria andCreditdateIsNotNull() {
            addCriterion("creditDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreditdateEqualTo(String value) {
            addCriterion("creditDate =", value, "creditdate");
            return (Criteria) this;
        }

        public Criteria andCreditdateNotEqualTo(String value) {
            addCriterion("creditDate <>", value, "creditdate");
            return (Criteria) this;
        }

        public Criteria andCreditdateGreaterThan(String value) {
            addCriterion("creditDate >", value, "creditdate");
            return (Criteria) this;
        }

        public Criteria andCreditdateGreaterThanOrEqualTo(String value) {
            addCriterion("creditDate >=", value, "creditdate");
            return (Criteria) this;
        }

        public Criteria andCreditdateLessThan(String value) {
            addCriterion("creditDate <", value, "creditdate");
            return (Criteria) this;
        }

        public Criteria andCreditdateLessThanOrEqualTo(String value) {
            addCriterion("creditDate <=", value, "creditdate");
            return (Criteria) this;
        }

        public Criteria andCreditdateLike(String value) {
            addCriterion("creditDate like", value, "creditdate");
            return (Criteria) this;
        }

        public Criteria andCreditdateNotLike(String value) {
            addCriterion("creditDate not like", value, "creditdate");
            return (Criteria) this;
        }

        public Criteria andCreditdateIn(List<String> values) {
            addCriterion("creditDate in", values, "creditdate");
            return (Criteria) this;
        }

        public Criteria andCreditdateNotIn(List<String> values) {
            addCriterion("creditDate not in", values, "creditdate");
            return (Criteria) this;
        }

        public Criteria andCreditdateBetween(String value1, String value2) {
            addCriterion("creditDate between", value1, value2, "creditdate");
            return (Criteria) this;
        }

        public Criteria andCreditdateNotBetween(String value1, String value2) {
            addCriterion("creditDate not between", value1, value2, "creditdate");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoIsNull() {
            addCriterion("FK_cgContractNo is null");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoIsNotNull() {
            addCriterion("FK_cgContractNo is not null");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoEqualTo(String value) {
            addCriterion("FK_cgContractNo =", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoNotEqualTo(String value) {
            addCriterion("FK_cgContractNo <>", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoGreaterThan(String value) {
            addCriterion("FK_cgContractNo >", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoGreaterThanOrEqualTo(String value) {
            addCriterion("FK_cgContractNo >=", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoLessThan(String value) {
            addCriterion("FK_cgContractNo <", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoLessThanOrEqualTo(String value) {
            addCriterion("FK_cgContractNo <=", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoLike(String value) {
            addCriterion("FK_cgContractNo like", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoNotLike(String value) {
            addCriterion("FK_cgContractNo not like", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoIn(List<String> values) {
            addCriterion("FK_cgContractNo in", values, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoNotIn(List<String> values) {
            addCriterion("FK_cgContractNo not in", values, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoBetween(String value1, String value2) {
            addCriterion("FK_cgContractNo between", value1, value2, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoNotBetween(String value1, String value2) {
            addCriterion("FK_cgContractNo not between", value1, value2, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIsNull() {
            addCriterion("FK_userNo is null");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIsNotNull() {
            addCriterion("FK_userNo is not null");
            return (Criteria) this;
        }

        public Criteria andFkUsernoEqualTo(String value) {
            addCriterion("FK_userNo =", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotEqualTo(String value) {
            addCriterion("FK_userNo <>", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoGreaterThan(String value) {
            addCriterion("FK_userNo >", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoGreaterThanOrEqualTo(String value) {
            addCriterion("FK_userNo >=", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLessThan(String value) {
            addCriterion("FK_userNo <", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLessThanOrEqualTo(String value) {
            addCriterion("FK_userNo <=", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLike(String value) {
            addCriterion("FK_userNo like", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotLike(String value) {
            addCriterion("FK_userNo not like", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIn(List<String> values) {
            addCriterion("FK_userNo in", values, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotIn(List<String> values) {
            addCriterion("FK_userNo not in", values, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoBetween(String value1, String value2) {
            addCriterion("FK_userNo between", value1, value2, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotBetween(String value1, String value2) {
            addCriterion("FK_userNo not between", value1, value2, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNull() {
            addCriterion("invalid is null");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNotNull() {
            addCriterion("invalid is not null");
            return (Criteria) this;
        }

        public Criteria andInvalidEqualTo(String value) {
            addCriterion("invalid =", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotEqualTo(String value) {
            addCriterion("invalid <>", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThan(String value) {
            addCriterion("invalid >", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThanOrEqualTo(String value) {
            addCriterion("invalid >=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThan(String value) {
            addCriterion("invalid <", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThanOrEqualTo(String value) {
            addCriterion("invalid <=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLike(String value) {
            addCriterion("invalid like", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotLike(String value) {
            addCriterion("invalid not like", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidIn(List<String> values) {
            addCriterion("invalid in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotIn(List<String> values) {
            addCriterion("invalid not in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidBetween(String value1, String value2) {
            addCriterion("invalid between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotBetween(String value1, String value2) {
            addCriterion("invalid not between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("createTime like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("createTime not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(String value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(String value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(String value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(String value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(String value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLike(String value) {
            addCriterion("updateTime like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotLike(String value) {
            addCriterion("updateTime not like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<String> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<String> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(String value1, String value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(String value1, String value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_cgcontractcredit
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}