package com.iboray.lms.domain.entity;

public class MResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresource.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresource.mresourceNo
     *
     * @mbggenerated
     */
    private String mresourceno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresource.mresourceName
     *
     * @mbggenerated
     */
    private String mresourcename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresource.mresourceValue
     *
     * @mbggenerated
     */
    private String mresourcevalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresource.mresourceUrl
     *
     * @mbggenerated
     */
    private String mresourceurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresource.FK_mresourceNo
     *
     * @mbggenerated
     */
    private String fkMresourceno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresource.invalid
     *
     * @mbggenerated
     */
    private String invalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresource.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresource.updateTime
     *
     * @mbggenerated
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresource.id
     *
     * @return the value of lm_a_mresource.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresource.id
     *
     * @param id the value for lm_a_mresource.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresource.mresourceNo
     *
     * @return the value of lm_a_mresource.mresourceNo
     *
     * @mbggenerated
     */
    public String getMresourceno() {
        return mresourceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresource.mresourceNo
     *
     * @param mresourceno the value for lm_a_mresource.mresourceNo
     *
     * @mbggenerated
     */
    public void setMresourceno(String mresourceno) {
        this.mresourceno = mresourceno == null ? null :  mresourceno.equals("")?null:mresourceno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresource.mresourceName
     *
     * @return the value of lm_a_mresource.mresourceName
     *
     * @mbggenerated
     */
    public String getMresourcename() {
        return mresourcename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresource.mresourceName
     *
     * @param mresourcename the value for lm_a_mresource.mresourceName
     *
     * @mbggenerated
     */
    public void setMresourcename(String mresourcename) {
        this.mresourcename = mresourcename == null ? null : mresourcename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresource.mresourceValue
     *
     * @return the value of lm_a_mresource.mresourceValue
     *
     * @mbggenerated
     */
    public String getMresourcevalue() {
        return mresourcevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresource.mresourceValue
     *
     * @param mresourcevalue the value for lm_a_mresource.mresourceValue
     *
     * @mbggenerated
     */
    public void setMresourcevalue(String mresourcevalue) {
        this.mresourcevalue = mresourcevalue == null ? null : mresourcevalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresource.mresourceUrl
     *
     * @return the value of lm_a_mresource.mresourceUrl
     *
     * @mbggenerated
     */
    public String getMresourceurl() {
        return mresourceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresource.mresourceUrl
     *
     * @param mresourceurl the value for lm_a_mresource.mresourceUrl
     *
     * @mbggenerated
     */
    public void setMresourceurl(String mresourceurl) {
        this.mresourceurl = mresourceurl == null ? null : mresourceurl.equals("")?null:mresourceurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresource.FK_mresourceNo
     *
     * @return the value of lm_a_mresource.FK_mresourceNo
     *
     * @mbggenerated
     */
    public String getFkMresourceno() {
        return fkMresourceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresource.FK_mresourceNo
     *
     * @param fkMresourceno the value for lm_a_mresource.FK_mresourceNo
     *
     * @mbggenerated
     */
    public void setFkMresourceno(String fkMresourceno) {
        this.fkMresourceno = fkMresourceno == null ? null : fkMresourceno.equals("")?null: fkMresourceno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresource.invalid
     *
     * @return the value of lm_a_mresource.invalid
     *
     * @mbggenerated
     */
    public String getInvalid() {
        return invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresource.invalid
     *
     * @param invalid the value for lm_a_mresource.invalid
     *
     * @mbggenerated
     */
    public void setInvalid(String invalid) {
        this.invalid = invalid == null ? null : invalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresource.createTime
     *
     * @return the value of lm_a_mresource.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresource.createTime
     *
     * @param createtime the value for lm_a_mresource.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresource.updateTime
     *
     * @return the value of lm_a_mresource.updateTime
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresource.updateTime
     *
     * @param updatetime the value for lm_a_mresource.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }
}