package com.iboray.lms.domain.entity;

public class MResourceRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresourcerole.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresourcerole.FK_mresourceNo
     *
     * @mbggenerated
     */
    private String fkMresourceno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresourcerole.FK_roleNo
     *
     * @mbggenerated
     */
    private String fkRoleno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresourcerole.invalid
     *
     * @mbggenerated
     */
    private String invalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresourcerole.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_mresourcerole.updateTime
     *
     * @mbggenerated
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresourcerole.id
     *
     * @return the value of lm_a_mresourcerole.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresourcerole.id
     *
     * @param id the value for lm_a_mresourcerole.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresourcerole.FK_mresourceNo
     *
     * @return the value of lm_a_mresourcerole.FK_mresourceNo
     *
     * @mbggenerated
     */
    public String getFkMresourceno() {
        return fkMresourceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresourcerole.FK_mresourceNo
     *
     * @param fkMresourceno the value for lm_a_mresourcerole.FK_mresourceNo
     *
     * @mbggenerated
     */
    public void setFkMresourceno(String fkMresourceno) {
        this.fkMresourceno = fkMresourceno == null ? null : fkMresourceno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresourcerole.FK_roleNo
     *
     * @return the value of lm_a_mresourcerole.FK_roleNo
     *
     * @mbggenerated
     */
    public String getFkRoleno() {
        return fkRoleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresourcerole.FK_roleNo
     *
     * @param fkRoleno the value for lm_a_mresourcerole.FK_roleNo
     *
     * @mbggenerated
     */
    public void setFkRoleno(String fkRoleno) {
        this.fkRoleno = fkRoleno == null ? null : fkRoleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresourcerole.invalid
     *
     * @return the value of lm_a_mresourcerole.invalid
     *
     * @mbggenerated
     */
    public String getInvalid() {
        return invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresourcerole.invalid
     *
     * @param invalid the value for lm_a_mresourcerole.invalid
     *
     * @mbggenerated
     */
    public void setInvalid(String invalid) {
        this.invalid = invalid == null ? null : invalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresourcerole.createTime
     *
     * @return the value of lm_a_mresourcerole.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresourcerole.createTime
     *
     * @param createtime the value for lm_a_mresourcerole.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_mresourcerole.updateTime
     *
     * @return the value of lm_a_mresourcerole.updateTime
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_mresourcerole.updateTime
     *
     * @param updatetime the value for lm_a_mresourcerole.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }
}