package com.iboray.lms.domain.entity;

import java.util.ArrayList;
import java.util.List;

public class MResourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    public MResourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMresourcenoIsNull() {
            addCriterion("mresourceNo is null");
            return (Criteria) this;
        }

        public Criteria andMresourcenoIsNotNull() {
            addCriterion("mresourceNo is not null");
            return (Criteria) this;
        }

        public Criteria andMresourcenoEqualTo(String value) {
            addCriterion("mresourceNo =", value, "mresourceno");
            return (Criteria) this;
        }

        public Criteria andMresourcenoNotEqualTo(String value) {
            addCriterion("mresourceNo <>", value, "mresourceno");
            return (Criteria) this;
        }

        public Criteria andMresourcenoGreaterThan(String value) {
            addCriterion("mresourceNo >", value, "mresourceno");
            return (Criteria) this;
        }

        public Criteria andMresourcenoGreaterThanOrEqualTo(String value) {
            addCriterion("mresourceNo >=", value, "mresourceno");
            return (Criteria) this;
        }

        public Criteria andMresourcenoLessThan(String value) {
            addCriterion("mresourceNo <", value, "mresourceno");
            return (Criteria) this;
        }

        public Criteria andMresourcenoLessThanOrEqualTo(String value) {
            addCriterion("mresourceNo <=", value, "mresourceno");
            return (Criteria) this;
        }

        public Criteria andMresourcenoLike(String value) {
            addCriterion("mresourceNo like", value, "mresourceno");
            return (Criteria) this;
        }

        public Criteria andMresourcenoNotLike(String value) {
            addCriterion("mresourceNo not like", value, "mresourceno");
            return (Criteria) this;
        }

        public Criteria andMresourcenoIn(List<String> values) {
            addCriterion("mresourceNo in", values, "mresourceno");
            return (Criteria) this;
        }

        public Criteria andMresourcenoNotIn(List<String> values) {
            addCriterion("mresourceNo not in", values, "mresourceno");
            return (Criteria) this;
        }

        public Criteria andMresourcenoBetween(String value1, String value2) {
            addCriterion("mresourceNo between", value1, value2, "mresourceno");
            return (Criteria) this;
        }

        public Criteria andMresourcenoNotBetween(String value1, String value2) {
            addCriterion("mresourceNo not between", value1, value2, "mresourceno");
            return (Criteria) this;
        }

        public Criteria andMresourcenameIsNull() {
            addCriterion("mresourceName is null");
            return (Criteria) this;
        }

        public Criteria andMresourcenameIsNotNull() {
            addCriterion("mresourceName is not null");
            return (Criteria) this;
        }

        public Criteria andMresourcenameEqualTo(String value) {
            addCriterion("mresourceName =", value, "mresourcename");
            return (Criteria) this;
        }

        public Criteria andMresourcenameNotEqualTo(String value) {
            addCriterion("mresourceName <>", value, "mresourcename");
            return (Criteria) this;
        }

        public Criteria andMresourcenameGreaterThan(String value) {
            addCriterion("mresourceName >", value, "mresourcename");
            return (Criteria) this;
        }

        public Criteria andMresourcenameGreaterThanOrEqualTo(String value) {
            addCriterion("mresourceName >=", value, "mresourcename");
            return (Criteria) this;
        }

        public Criteria andMresourcenameLessThan(String value) {
            addCriterion("mresourceName <", value, "mresourcename");
            return (Criteria) this;
        }

        public Criteria andMresourcenameLessThanOrEqualTo(String value) {
            addCriterion("mresourceName <=", value, "mresourcename");
            return (Criteria) this;
        }

        public Criteria andMresourcenameLike(String value) {
            addCriterion("mresourceName like", value, "mresourcename");
            return (Criteria) this;
        }

        public Criteria andMresourcenameNotLike(String value) {
            addCriterion("mresourceName not like", value, "mresourcename");
            return (Criteria) this;
        }

        public Criteria andMresourcenameIn(List<String> values) {
            addCriterion("mresourceName in", values, "mresourcename");
            return (Criteria) this;
        }

        public Criteria andMresourcenameNotIn(List<String> values) {
            addCriterion("mresourceName not in", values, "mresourcename");
            return (Criteria) this;
        }

        public Criteria andMresourcenameBetween(String value1, String value2) {
            addCriterion("mresourceName between", value1, value2, "mresourcename");
            return (Criteria) this;
        }

        public Criteria andMresourcenameNotBetween(String value1, String value2) {
            addCriterion("mresourceName not between", value1, value2, "mresourcename");
            return (Criteria) this;
        }

        public Criteria andMresourcevalueIsNull() {
            addCriterion("mresourceValue is null");
            return (Criteria) this;
        }

        public Criteria andMresourcevalueIsNotNull() {
            addCriterion("mresourceValue is not null");
            return (Criteria) this;
        }

        public Criteria andMresourcevalueEqualTo(String value) {
            addCriterion("mresourceValue =", value, "mresourcevalue");
            return (Criteria) this;
        }

        public Criteria andMresourcevalueNotEqualTo(String value) {
            addCriterion("mresourceValue <>", value, "mresourcevalue");
            return (Criteria) this;
        }

        public Criteria andMresourcevalueGreaterThan(String value) {
            addCriterion("mresourceValue >", value, "mresourcevalue");
            return (Criteria) this;
        }

        public Criteria andMresourcevalueGreaterThanOrEqualTo(String value) {
            addCriterion("mresourceValue >=", value, "mresourcevalue");
            return (Criteria) this;
        }

        public Criteria andMresourcevalueLessThan(String value) {
            addCriterion("mresourceValue <", value, "mresourcevalue");
            return (Criteria) this;
        }

        public Criteria andMresourcevalueLessThanOrEqualTo(String value) {
            addCriterion("mresourceValue <=", value, "mresourcevalue");
            return (Criteria) this;
        }

        public Criteria andMresourcevalueLike(String value) {
            addCriterion("mresourceValue like", value, "mresourcevalue");
            return (Criteria) this;
        }

        public Criteria andMresourcevalueNotLike(String value) {
            addCriterion("mresourceValue not like", value, "mresourcevalue");
            return (Criteria) this;
        }

        public Criteria andMresourcevalueIn(List<String> values) {
            addCriterion("mresourceValue in", values, "mresourcevalue");
            return (Criteria) this;
        }

        public Criteria andMresourcevalueNotIn(List<String> values) {
            addCriterion("mresourceValue not in", values, "mresourcevalue");
            return (Criteria) this;
        }

        public Criteria andMresourcevalueBetween(String value1, String value2) {
            addCriterion("mresourceValue between", value1, value2, "mresourcevalue");
            return (Criteria) this;
        }

        public Criteria andMresourcevalueNotBetween(String value1, String value2) {
            addCriterion("mresourceValue not between", value1, value2, "mresourcevalue");
            return (Criteria) this;
        }

        public Criteria andMresourceurlIsNull() {
            addCriterion("mresourceUrl is null");
            return (Criteria) this;
        }

        public Criteria andMresourceurlIsNotNull() {
            addCriterion("mresourceUrl is not null");
            return (Criteria) this;
        }

        public Criteria andMresourceurlEqualTo(String value) {
            addCriterion("mresourceUrl =", value, "mresourceurl");
            return (Criteria) this;
        }

        public Criteria andMresourceurlNotEqualTo(String value) {
            addCriterion("mresourceUrl <>", value, "mresourceurl");
            return (Criteria) this;
        }

        public Criteria andMresourceurlGreaterThan(String value) {
            addCriterion("mresourceUrl >", value, "mresourceurl");
            return (Criteria) this;
        }

        public Criteria andMresourceurlGreaterThanOrEqualTo(String value) {
            addCriterion("mresourceUrl >=", value, "mresourceurl");
            return (Criteria) this;
        }

        public Criteria andMresourceurlLessThan(String value) {
            addCriterion("mresourceUrl <", value, "mresourceurl");
            return (Criteria) this;
        }

        public Criteria andMresourceurlLessThanOrEqualTo(String value) {
            addCriterion("mresourceUrl <=", value, "mresourceurl");
            return (Criteria) this;
        }

        public Criteria andMresourceurlLike(String value) {
            addCriterion("mresourceUrl like", value, "mresourceurl");
            return (Criteria) this;
        }

        public Criteria andMresourceurlNotLike(String value) {
            addCriterion("mresourceUrl not like", value, "mresourceurl");
            return (Criteria) this;
        }

        public Criteria andMresourceurlIn(List<String> values) {
            addCriterion("mresourceUrl in", values, "mresourceurl");
            return (Criteria) this;
        }

        public Criteria andMresourceurlNotIn(List<String> values) {
            addCriterion("mresourceUrl not in", values, "mresourceurl");
            return (Criteria) this;
        }

        public Criteria andMresourceurlBetween(String value1, String value2) {
            addCriterion("mresourceUrl between", value1, value2, "mresourceurl");
            return (Criteria) this;
        }

        public Criteria andMresourceurlNotBetween(String value1, String value2) {
            addCriterion("mresourceUrl not between", value1, value2, "mresourceurl");
            return (Criteria) this;
        }

        public Criteria andFkMresourcenoIsNull() {
            addCriterion("FK_mresourceNo is null");
            return (Criteria) this;
        }

        public Criteria andFkMresourcenoIsNotNull() {
            addCriterion("FK_mresourceNo is not null");
            return (Criteria) this;
        }

        public Criteria andFkMresourcenoEqualTo(String value) {
            addCriterion("FK_mresourceNo =", value, "fkMresourceno");
            return (Criteria) this;
        }

        public Criteria andFkMresourcenoNotEqualTo(String value) {
            addCriterion("FK_mresourceNo <>", value, "fkMresourceno");
            return (Criteria) this;
        }

        public Criteria andFkMresourcenoGreaterThan(String value) {
            addCriterion("FK_mresourceNo >", value, "fkMresourceno");
            return (Criteria) this;
        }

        public Criteria andFkMresourcenoGreaterThanOrEqualTo(String value) {
            addCriterion("FK_mresourceNo >=", value, "fkMresourceno");
            return (Criteria) this;
        }

        public Criteria andFkMresourcenoLessThan(String value) {
            addCriterion("FK_mresourceNo <", value, "fkMresourceno");
            return (Criteria) this;
        }

        public Criteria andFkMresourcenoLessThanOrEqualTo(String value) {
            addCriterion("FK_mresourceNo <=", value, "fkMresourceno");
            return (Criteria) this;
        }

        public Criteria andFkMresourcenoLike(String value) {
            addCriterion("FK_mresourceNo like", value, "fkMresourceno");
            return (Criteria) this;
        }

        public Criteria andFkMresourcenoNotLike(String value) {
            addCriterion("FK_mresourceNo not like", value, "fkMresourceno");
            return (Criteria) this;
        }

        public Criteria andFkMresourcenoIn(List<String> values) {
            addCriterion("FK_mresourceNo in", values, "fkMresourceno");
            return (Criteria) this;
        }

        public Criteria andFkMresourcenoNotIn(List<String> values) {
            addCriterion("FK_mresourceNo not in", values, "fkMresourceno");
            return (Criteria) this;
        }

        public Criteria andFkMresourcenoBetween(String value1, String value2) {
            addCriterion("FK_mresourceNo between", value1, value2, "fkMresourceno");
            return (Criteria) this;
        }

        public Criteria andFkMresourcenoNotBetween(String value1, String value2) {
            addCriterion("FK_mresourceNo not between", value1, value2, "fkMresourceno");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNull() {
            addCriterion("invalid is null");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNotNull() {
            addCriterion("invalid is not null");
            return (Criteria) this;
        }

        public Criteria andInvalidEqualTo(String value) {
            addCriterion("invalid =", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotEqualTo(String value) {
            addCriterion("invalid <>", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThan(String value) {
            addCriterion("invalid >", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThanOrEqualTo(String value) {
            addCriterion("invalid >=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThan(String value) {
            addCriterion("invalid <", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThanOrEqualTo(String value) {
            addCriterion("invalid <=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLike(String value) {
            addCriterion("invalid like", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotLike(String value) {
            addCriterion("invalid not like", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidIn(List<String> values) {
            addCriterion("invalid in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotIn(List<String> values) {
            addCriterion("invalid not in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidBetween(String value1, String value2) {
            addCriterion("invalid between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotBetween(String value1, String value2) {
            addCriterion("invalid not between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("createTime like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("createTime not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(String value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(String value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(String value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(String value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(String value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLike(String value) {
            addCriterion("updateTime like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotLike(String value) {
            addCriterion("updateTime not like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<String> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<String> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(String value1, String value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(String value1, String value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_a_mresource
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_a_mresource
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}