package com.iboray.lms.domain.entity;

public class Payed {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_payed.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_payed.payedNo
     *
     * @mbggenerated
     */
    private String payedno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_payed.payedMoney
     *
     * @mbggenerated
     */
    private Double payedmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_payed.payedWay
     *
     * @mbggenerated
     */
    private String payedway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_payed.payedDate
     *
     * @mbggenerated
     */
    private String payeddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_payed.FK_cgContractNo
     *
     * @mbggenerated
     */
    private String fkCgcontractno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_payed.FK_userNo
     *
     * @mbggenerated
     */
    private String fkUserno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_payed.invalid
     *
     * @mbggenerated
     */
    private String invalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_payed.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_payed.updateTime
     *
     * @mbggenerated
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_payed.id
     *
     * @return the value of lm_d_payed.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_payed.id
     *
     * @param id the value for lm_d_payed.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_payed.payedNo
     *
     * @return the value of lm_d_payed.payedNo
     *
     * @mbggenerated
     */
    public String getPayedno() {
        return payedno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_payed.payedNo
     *
     * @param payedno the value for lm_d_payed.payedNo
     *
     * @mbggenerated
     */
    public void setPayedno(String payedno) {
        this.payedno = payedno == null ? null : payedno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_payed.payedMoney
     *
     * @return the value of lm_d_payed.payedMoney
     *
     * @mbggenerated
     */
    public Double getPayedmoney() {
        return payedmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_payed.payedMoney
     *
     * @param payedmoney the value for lm_d_payed.payedMoney
     *
     * @mbggenerated
     */
    public void setPayedmoney(Double payedmoney) {
        this.payedmoney = payedmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_payed.payedWay
     *
     * @return the value of lm_d_payed.payedWay
     *
     * @mbggenerated
     */
    public String getPayedway() {
        return payedway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_payed.payedWay
     *
     * @param payedway the value for lm_d_payed.payedWay
     *
     * @mbggenerated
     */
    public void setPayedway(String payedway) {
        this.payedway = payedway == null ? null : payedway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_payed.payedDate
     *
     * @return the value of lm_d_payed.payedDate
     *
     * @mbggenerated
     */
    public String getPayeddate() {
        return payeddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_payed.payedDate
     *
     * @param payeddate the value for lm_d_payed.payedDate
     *
     * @mbggenerated
     */
    public void setPayeddate(String payeddate) {
        this.payeddate = payeddate == null ? null : payeddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_payed.FK_cgContractNo
     *
     * @return the value of lm_d_payed.FK_cgContractNo
     *
     * @mbggenerated
     */
    public String getFkCgcontractno() {
        return fkCgcontractno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_payed.FK_cgContractNo
     *
     * @param fkCgcontractno the value for lm_d_payed.FK_cgContractNo
     *
     * @mbggenerated
     */
    public void setFkCgcontractno(String fkCgcontractno) {
        this.fkCgcontractno = fkCgcontractno == null ? null : fkCgcontractno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_payed.FK_userNo
     *
     * @return the value of lm_d_payed.FK_userNo
     *
     * @mbggenerated
     */
    public String getFkUserno() {
        return fkUserno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_payed.FK_userNo
     *
     * @param fkUserno the value for lm_d_payed.FK_userNo
     *
     * @mbggenerated
     */
    public void setFkUserno(String fkUserno) {
        this.fkUserno = fkUserno == null ? null : fkUserno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_payed.invalid
     *
     * @return the value of lm_d_payed.invalid
     *
     * @mbggenerated
     */
    public String getInvalid() {
        return invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_payed.invalid
     *
     * @param invalid the value for lm_d_payed.invalid
     *
     * @mbggenerated
     */
    public void setInvalid(String invalid) {
        this.invalid = invalid == null ? null : invalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_payed.createTime
     *
     * @return the value of lm_d_payed.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_payed.createTime
     *
     * @param createtime the value for lm_d_payed.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_payed.updateTime
     *
     * @return the value of lm_d_payed.updateTime
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_payed.updateTime
     *
     * @param updatetime the value for lm_d_payed.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }
}