package com.iboray.lms.domain.entity;

import java.util.ArrayList;
import java.util.List;

public class PayedExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    public PayedExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPayednoIsNull() {
            addCriterion("payedNo is null");
            return (Criteria) this;
        }

        public Criteria andPayednoIsNotNull() {
            addCriterion("payedNo is not null");
            return (Criteria) this;
        }

        public Criteria andPayednoEqualTo(String value) {
            addCriterion("payedNo =", value, "payedno");
            return (Criteria) this;
        }

        public Criteria andPayednoNotEqualTo(String value) {
            addCriterion("payedNo <>", value, "payedno");
            return (Criteria) this;
        }

        public Criteria andPayednoGreaterThan(String value) {
            addCriterion("payedNo >", value, "payedno");
            return (Criteria) this;
        }

        public Criteria andPayednoGreaterThanOrEqualTo(String value) {
            addCriterion("payedNo >=", value, "payedno");
            return (Criteria) this;
        }

        public Criteria andPayednoLessThan(String value) {
            addCriterion("payedNo <", value, "payedno");
            return (Criteria) this;
        }

        public Criteria andPayednoLessThanOrEqualTo(String value) {
            addCriterion("payedNo <=", value, "payedno");
            return (Criteria) this;
        }

        public Criteria andPayednoLike(String value) {
            addCriterion("payedNo like", value, "payedno");
            return (Criteria) this;
        }

        public Criteria andPayednoNotLike(String value) {
            addCriterion("payedNo not like", value, "payedno");
            return (Criteria) this;
        }

        public Criteria andPayednoIn(List<String> values) {
            addCriterion("payedNo in", values, "payedno");
            return (Criteria) this;
        }

        public Criteria andPayednoNotIn(List<String> values) {
            addCriterion("payedNo not in", values, "payedno");
            return (Criteria) this;
        }

        public Criteria andPayednoBetween(String value1, String value2) {
            addCriterion("payedNo between", value1, value2, "payedno");
            return (Criteria) this;
        }

        public Criteria andPayednoNotBetween(String value1, String value2) {
            addCriterion("payedNo not between", value1, value2, "payedno");
            return (Criteria) this;
        }

        public Criteria andPayedmoneyIsNull() {
            addCriterion("payedMoney is null");
            return (Criteria) this;
        }

        public Criteria andPayedmoneyIsNotNull() {
            addCriterion("payedMoney is not null");
            return (Criteria) this;
        }

        public Criteria andPayedmoneyEqualTo(Double value) {
            addCriterion("payedMoney =", value, "payedmoney");
            return (Criteria) this;
        }

        public Criteria andPayedmoneyNotEqualTo(Double value) {
            addCriterion("payedMoney <>", value, "payedmoney");
            return (Criteria) this;
        }

        public Criteria andPayedmoneyGreaterThan(Double value) {
            addCriterion("payedMoney >", value, "payedmoney");
            return (Criteria) this;
        }

        public Criteria andPayedmoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("payedMoney >=", value, "payedmoney");
            return (Criteria) this;
        }

        public Criteria andPayedmoneyLessThan(Double value) {
            addCriterion("payedMoney <", value, "payedmoney");
            return (Criteria) this;
        }

        public Criteria andPayedmoneyLessThanOrEqualTo(Double value) {
            addCriterion("payedMoney <=", value, "payedmoney");
            return (Criteria) this;
        }

        public Criteria andPayedmoneyIn(List<Double> values) {
            addCriterion("payedMoney in", values, "payedmoney");
            return (Criteria) this;
        }

        public Criteria andPayedmoneyNotIn(List<Double> values) {
            addCriterion("payedMoney not in", values, "payedmoney");
            return (Criteria) this;
        }

        public Criteria andPayedmoneyBetween(Double value1, Double value2) {
            addCriterion("payedMoney between", value1, value2, "payedmoney");
            return (Criteria) this;
        }

        public Criteria andPayedmoneyNotBetween(Double value1, Double value2) {
            addCriterion("payedMoney not between", value1, value2, "payedmoney");
            return (Criteria) this;
        }

        public Criteria andPayedwayIsNull() {
            addCriterion("payedWay is null");
            return (Criteria) this;
        }

        public Criteria andPayedwayIsNotNull() {
            addCriterion("payedWay is not null");
            return (Criteria) this;
        }

        public Criteria andPayedwayEqualTo(String value) {
            addCriterion("payedWay =", value, "payedway");
            return (Criteria) this;
        }

        public Criteria andPayedwayNotEqualTo(String value) {
            addCriterion("payedWay <>", value, "payedway");
            return (Criteria) this;
        }

        public Criteria andPayedwayGreaterThan(String value) {
            addCriterion("payedWay >", value, "payedway");
            return (Criteria) this;
        }

        public Criteria andPayedwayGreaterThanOrEqualTo(String value) {
            addCriterion("payedWay >=", value, "payedway");
            return (Criteria) this;
        }

        public Criteria andPayedwayLessThan(String value) {
            addCriterion("payedWay <", value, "payedway");
            return (Criteria) this;
        }

        public Criteria andPayedwayLessThanOrEqualTo(String value) {
            addCriterion("payedWay <=", value, "payedway");
            return (Criteria) this;
        }

        public Criteria andPayedwayLike(String value) {
            addCriterion("payedWay like", value, "payedway");
            return (Criteria) this;
        }

        public Criteria andPayedwayNotLike(String value) {
            addCriterion("payedWay not like", value, "payedway");
            return (Criteria) this;
        }

        public Criteria andPayedwayIn(List<String> values) {
            addCriterion("payedWay in", values, "payedway");
            return (Criteria) this;
        }

        public Criteria andPayedwayNotIn(List<String> values) {
            addCriterion("payedWay not in", values, "payedway");
            return (Criteria) this;
        }

        public Criteria andPayedwayBetween(String value1, String value2) {
            addCriterion("payedWay between", value1, value2, "payedway");
            return (Criteria) this;
        }

        public Criteria andPayedwayNotBetween(String value1, String value2) {
            addCriterion("payedWay not between", value1, value2, "payedway");
            return (Criteria) this;
        }

        public Criteria andPayeddateIsNull() {
            addCriterion("payedDate is null");
            return (Criteria) this;
        }

        public Criteria andPayeddateIsNotNull() {
            addCriterion("payedDate is not null");
            return (Criteria) this;
        }

        public Criteria andPayeddateEqualTo(String value) {
            addCriterion("payedDate =", value, "payeddate");
            return (Criteria) this;
        }

        public Criteria andPayeddateNotEqualTo(String value) {
            addCriterion("payedDate <>", value, "payeddate");
            return (Criteria) this;
        }

        public Criteria andPayeddateGreaterThan(String value) {
            addCriterion("payedDate >", value, "payeddate");
            return (Criteria) this;
        }

        public Criteria andPayeddateGreaterThanOrEqualTo(String value) {
            addCriterion("payedDate >=", value, "payeddate");
            return (Criteria) this;
        }

        public Criteria andPayeddateLessThan(String value) {
            addCriterion("payedDate <", value, "payeddate");
            return (Criteria) this;
        }

        public Criteria andPayeddateLessThanOrEqualTo(String value) {
            addCriterion("payedDate <=", value, "payeddate");
            return (Criteria) this;
        }

        public Criteria andPayeddateLike(String value) {
            addCriterion("payedDate like", value, "payeddate");
            return (Criteria) this;
        }

        public Criteria andPayeddateNotLike(String value) {
            addCriterion("payedDate not like", value, "payeddate");
            return (Criteria) this;
        }

        public Criteria andPayeddateIn(List<String> values) {
            addCriterion("payedDate in", values, "payeddate");
            return (Criteria) this;
        }

        public Criteria andPayeddateNotIn(List<String> values) {
            addCriterion("payedDate not in", values, "payeddate");
            return (Criteria) this;
        }

        public Criteria andPayeddateBetween(String value1, String value2) {
            addCriterion("payedDate between", value1, value2, "payeddate");
            return (Criteria) this;
        }

        public Criteria andPayeddateNotBetween(String value1, String value2) {
            addCriterion("payedDate not between", value1, value2, "payeddate");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoIsNull() {
            addCriterion("FK_cgContractNo is null");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoIsNotNull() {
            addCriterion("FK_cgContractNo is not null");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoEqualTo(String value) {
            addCriterion("FK_cgContractNo =", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoNotEqualTo(String value) {
            addCriterion("FK_cgContractNo <>", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoGreaterThan(String value) {
            addCriterion("FK_cgContractNo >", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoGreaterThanOrEqualTo(String value) {
            addCriterion("FK_cgContractNo >=", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoLessThan(String value) {
            addCriterion("FK_cgContractNo <", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoLessThanOrEqualTo(String value) {
            addCriterion("FK_cgContractNo <=", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoLike(String value) {
            addCriterion("FK_cgContractNo like", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoNotLike(String value) {
            addCriterion("FK_cgContractNo not like", value, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoIn(List<String> values) {
            addCriterion("FK_cgContractNo in", values, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoNotIn(List<String> values) {
            addCriterion("FK_cgContractNo not in", values, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoBetween(String value1, String value2) {
            addCriterion("FK_cgContractNo between", value1, value2, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkCgcontractnoNotBetween(String value1, String value2) {
            addCriterion("FK_cgContractNo not between", value1, value2, "fkCgcontractno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIsNull() {
            addCriterion("FK_userNo is null");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIsNotNull() {
            addCriterion("FK_userNo is not null");
            return (Criteria) this;
        }

        public Criteria andFkUsernoEqualTo(String value) {
            addCriterion("FK_userNo =", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotEqualTo(String value) {
            addCriterion("FK_userNo <>", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoGreaterThan(String value) {
            addCriterion("FK_userNo >", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoGreaterThanOrEqualTo(String value) {
            addCriterion("FK_userNo >=", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLessThan(String value) {
            addCriterion("FK_userNo <", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLessThanOrEqualTo(String value) {
            addCriterion("FK_userNo <=", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLike(String value) {
            addCriterion("FK_userNo like", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotLike(String value) {
            addCriterion("FK_userNo not like", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIn(List<String> values) {
            addCriterion("FK_userNo in", values, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotIn(List<String> values) {
            addCriterion("FK_userNo not in", values, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoBetween(String value1, String value2) {
            addCriterion("FK_userNo between", value1, value2, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotBetween(String value1, String value2) {
            addCriterion("FK_userNo not between", value1, value2, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNull() {
            addCriterion("invalid is null");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNotNull() {
            addCriterion("invalid is not null");
            return (Criteria) this;
        }

        public Criteria andInvalidEqualTo(String value) {
            addCriterion("invalid =", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotEqualTo(String value) {
            addCriterion("invalid <>", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThan(String value) {
            addCriterion("invalid >", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThanOrEqualTo(String value) {
            addCriterion("invalid >=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThan(String value) {
            addCriterion("invalid <", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThanOrEqualTo(String value) {
            addCriterion("invalid <=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLike(String value) {
            addCriterion("invalid like", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotLike(String value) {
            addCriterion("invalid not like", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidIn(List<String> values) {
            addCriterion("invalid in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotIn(List<String> values) {
            addCriterion("invalid not in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidBetween(String value1, String value2) {
            addCriterion("invalid between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotBetween(String value1, String value2) {
            addCriterion("invalid not between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("createTime like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("createTime not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(String value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(String value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(String value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(String value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(String value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLike(String value) {
            addCriterion("updateTime like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotLike(String value) {
            addCriterion("updateTime not like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<String> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<String> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(String value1, String value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(String value1, String value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_payed
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_payed
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}