package com.iboray.lms.domain.entity;

public class PlanProcurementSource {
    private Integer id;
    private String planno;
    private String itemscode;
    private String itemsname;
    private String cartcode;
    private Integer cartlinenum;
    private String oldplannum;
    private Integer oldplanlinenum;
    private String fkUsecompno;
    private String receiptdate;
    private String unit;
    private Double plannum;
    private Double planprice;
    private Double planmoney;
    private String arrivaldate;
    private String arrivaladdr;
    private String planstatus;
    private String bnumber;
    private String fnumber;
    private String fkDtypeno;
    private String fkZtypeno;
    private String fkXtypeno;
    private Double searchprice;
    private Double searchmoney;
    private String fkProcurementno;
    private Double salesmoney;
    private String fkCgcontractno;
    private String fkXscontractno;
    private String fkDlcontractno;
    private String fkUserno;
    private String fkDeptno;
    private String invalid;
    private String createtime;
    private String updatetime;
    private String procurementno;
    private String procurementname;
    private String procurementwaycode;
    private String procurementcreatedate;
    private String procurementauditdate;
    private String searchannounceddate;
    private String searchauditdate;
    private String executionwaycode;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPlanno() {
        return planno;
    }
    public void setPlanno(String planno) {
        this.planno = planno == null ? null : planno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.itemsCode
     *
     * @return the value of lm_d_plan.itemsCode
     *
     * @mbggenerated
     */
    public String getItemscode() {
        return itemscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.itemsCode
     *
     * @param itemscode the value for lm_d_plan.itemsCode
     *
     * @mbggenerated
     */
    public void setItemscode(String itemscode) {
        this.itemscode = itemscode == null ? null : itemscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.itemsName
     *
     * @return the value of lm_d_plan.itemsName
     *
     * @mbggenerated
     */
    public String getItemsname() {
        return itemsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.itemsName
     *
     * @param itemsname the value for lm_d_plan.itemsName
     *
     * @mbggenerated
     */
    public void setItemsname(String itemsname) {
        this.itemsname = itemsname == null ? null : itemsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.cartCode
     *
     * @return the value of lm_d_plan.cartCode
     *
     * @mbggenerated
     */
    public String getCartcode() {
        return cartcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.cartCode
     *
     * @param cartcode the value for lm_d_plan.cartCode
     *
     * @mbggenerated
     */
    public void setCartcode(String cartcode) {
        this.cartcode = cartcode == null ? null : cartcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.cartlineNum
     *
     * @return the value of lm_d_plan.cartlineNum
     *
     * @mbggenerated
     */
    public Integer getCartlinenum() {
        return cartlinenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.cartlineNum
     *
     * @param cartlinenum the value for lm_d_plan.cartlineNum
     *
     * @mbggenerated
     */
    public void setCartlinenum(Integer cartlinenum) {
        this.cartlinenum = cartlinenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.oldPlanNum
     *
     * @return the value of lm_d_plan.oldPlanNum
     *
     * @mbggenerated
     */
    public String getOldplannum() {
        return oldplannum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.oldPlanNum
     *
     * @param oldplannum the value for lm_d_plan.oldPlanNum
     *
     * @mbggenerated
     */
    public void setOldplannum(String oldplannum) {
        this.oldplannum = oldplannum == null ? null : oldplannum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.oldPlanlineNum
     *
     * @return the value of lm_d_plan.oldPlanlineNum
     *
     * @mbggenerated
     */
    public Integer getOldplanlinenum() {
        return oldplanlinenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.oldPlanlineNum
     *
     * @param oldplanlinenum the value for lm_d_plan.oldPlanlineNum
     *
     * @mbggenerated
     */
    public void setOldplanlinenum(Integer oldplanlinenum) {
        this.oldplanlinenum = oldplanlinenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.FK_usecompNo
     *
     * @return the value of lm_d_plan.FK_usecompNo
     *
     * @mbggenerated
     */
    public String getFkUsecompno() {
        return fkUsecompno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.FK_usecompNo
     *
     * @param fkUsecompno the value for lm_d_plan.FK_usecompNo
     *
     * @mbggenerated
     */
    public void setFkUsecompno(String fkUsecompno) {
        this.fkUsecompno = fkUsecompno == null ? null : fkUsecompno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.ReceiptDate
     *
     * @return the value of lm_d_plan.ReceiptDate
     *
     * @mbggenerated
     */
    public String getReceiptdate() {
        return receiptdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.ReceiptDate
     *
     * @param receiptdate the value for lm_d_plan.ReceiptDate
     *
     * @mbggenerated
     */
    public void setReceiptdate(String receiptdate) {
        this.receiptdate = receiptdate == null ? null : receiptdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.unit
     *
     * @return the value of lm_d_plan.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.unit
     *
     * @param unit the value for lm_d_plan.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.planNum
     *
     * @return the value of lm_d_plan.planNum
     *
     * @mbggenerated
     */
    public Double getPlannum() {
        return plannum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.planNum
     *
     * @param plannum the value for lm_d_plan.planNum
     *
     * @mbggenerated
     */
    public void setPlannum(Double plannum) {
        this.plannum = plannum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.planPrice
     *
     * @return the value of lm_d_plan.planPrice
     *
     * @mbggenerated
     */
    public Double getPlanprice() {
        return planprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.planPrice
     *
     * @param planprice the value for lm_d_plan.planPrice
     *
     * @mbggenerated
     */
    public void setPlanprice(Double planprice) {
        this.planprice = planprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.planMoney
     *
     * @return the value of lm_d_plan.planMoney
     *
     * @mbggenerated
     */
    public Double getPlanmoney() {
        return planmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.planMoney
     *
     * @param planmoney the value for lm_d_plan.planMoney
     *
     * @mbggenerated
     */
    public void setPlanmoney(Double planmoney) {
        this.planmoney = planmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.arrivalDate
     *
     * @return the value of lm_d_plan.arrivalDate
     *
     * @mbggenerated
     */
    public String getArrivaldate() {
        return arrivaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.arrivalDate
     *
     * @param arrivaldate the value for lm_d_plan.arrivalDate
     *
     * @mbggenerated
     */
    public void setArrivaldate(String arrivaldate) {
        this.arrivaldate = arrivaldate == null ? null : arrivaldate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.arrivalAddr
     *
     * @return the value of lm_d_plan.arrivalAddr
     *
     * @mbggenerated
     */
    public String getArrivaladdr() {
        return arrivaladdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.arrivalAddr
     *
     * @param arrivaladdr the value for lm_d_plan.arrivalAddr
     *
     * @mbggenerated
     */
    public void setArrivaladdr(String arrivaladdr) {
        this.arrivaladdr = arrivaladdr == null ? null : arrivaladdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.planStatus
     *
     * @return the value of lm_d_plan.planStatus
     *
     * @mbggenerated
     */
    public String getPlanstatus() {
        return planstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.planStatus
     *
     * @param planstatus the value for lm_d_plan.planStatus
     *
     * @mbggenerated
     */
    public void setPlanstatus(String planstatus) {
        this.planstatus = planstatus == null ? null : planstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.bNumber
     *
     * @return the value of lm_d_plan.bNumber
     *
     * @mbggenerated
     */
    public String getBnumber() {
        return bnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.bNumber
     *
     * @param bnumber the value for lm_d_plan.bNumber
     *
     * @mbggenerated
     */
    public void setBnumber(String bnumber) {
        this.bnumber = bnumber == null ? null : bnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.fNumber
     *
     * @return the value of lm_d_plan.fNumber
     *
     * @mbggenerated
     */
    public String getFnumber() {
        return fnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.fNumber
     *
     * @param fnumber the value for lm_d_plan.fNumber
     *
     * @mbggenerated
     */
    public void setFnumber(String fnumber) {
        this.fnumber = fnumber == null ? null : fnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.FK_dTypeNo
     *
     * @return the value of lm_d_plan.FK_dTypeNo
     *
     * @mbggenerated
     */
    public String getFkDtypeno() {
        return fkDtypeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.FK_dTypeNo
     *
     * @param fkDtypeno the value for lm_d_plan.FK_dTypeNo
     *
     * @mbggenerated
     */
    public void setFkDtypeno(String fkDtypeno) {
        this.fkDtypeno = fkDtypeno == null ? null : fkDtypeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.FK_zTypeNo
     *
     * @return the value of lm_d_plan.FK_zTypeNo
     *
     * @mbggenerated
     */
    public String getFkZtypeno() {
        return fkZtypeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.FK_zTypeNo
     *
     * @param fkZtypeno the value for lm_d_plan.FK_zTypeNo
     *
     * @mbggenerated
     */
    public void setFkZtypeno(String fkZtypeno) {
        this.fkZtypeno = fkZtypeno == null ? null : fkZtypeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.FK_xTypeNo
     *
     * @return the value of lm_d_plan.FK_xTypeNo
     *
     * @mbggenerated
     */
    public String getFkXtypeno() {
        return fkXtypeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.FK_xTypeNo
     *
     * @param fkXtypeno the value for lm_d_plan.FK_xTypeNo
     *
     * @mbggenerated
     */
    public void setFkXtypeno(String fkXtypeno) {
        this.fkXtypeno = fkXtypeno == null ? null : fkXtypeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.searchPrice
     *
     * @return the value of lm_d_plan.searchPrice
     *
     * @mbggenerated
     */
    public Double getSearchprice() {
        return searchprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.searchPrice
     *
     * @param searchprice the value for lm_d_plan.searchPrice
     *
     * @mbggenerated
     */
    public void setSearchprice(Double searchprice) {
        this.searchprice = searchprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.searchMoney
     *
     * @return the value of lm_d_plan.searchMoney
     *
     * @mbggenerated
     */
    public Double getSearchmoney() {
        return searchmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.searchMoney
     *
     * @param searchmoney the value for lm_d_plan.searchMoney
     *
     * @mbggenerated
     */
    public void setSearchmoney(Double searchmoney) {
        this.searchmoney = searchmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.FK_procurementNo
     *
     * @return the value of lm_d_plan.FK_procurementNo
     *
     * @mbggenerated
     */
    public String getFkProcurementno() {
        return fkProcurementno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.FK_procurementNo
     *
     * @param fkProcurementno the value for lm_d_plan.FK_procurementNo
     *
     * @mbggenerated
     */
    public void setFkProcurementno(String fkProcurementno) {
        this.fkProcurementno = fkProcurementno == null ? null : fkProcurementno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.salesMoney
     *
     * @return the value of lm_d_plan.salesMoney
     *
     * @mbggenerated
     */
    public Double getSalesmoney() {
        return salesmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.salesMoney
     *
     * @param salesmoney the value for lm_d_plan.salesMoney
     *
     * @mbggenerated
     */
    public void setSalesmoney(Double salesmoney) {
        this.salesmoney = salesmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.FK_cgContractNo
     *
     * @return the value of lm_d_plan.FK_cgContractNo
     *
     * @mbggenerated
     */
    public String getFkCgcontractno() {
        return fkCgcontractno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.FK_cgContractNo
     *
     * @param fkCgcontractno the value for lm_d_plan.FK_cgContractNo
     *
     * @mbggenerated
     */
    public void setFkCgcontractno(String fkCgcontractno) {
        this.fkCgcontractno = fkCgcontractno == null ? null : fkCgcontractno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.FK_xsContractNo
     *
     * @return the value of lm_d_plan.FK_xsContractNo
     *
     * @mbggenerated
     */
    public String getFkXscontractno() {
        return fkXscontractno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.FK_xsContractNo
     *
     * @param fkXscontractno the value for lm_d_plan.FK_xsContractNo
     *
     * @mbggenerated
     */
    public void setFkXscontractno(String fkXscontractno) {
        this.fkXscontractno = fkXscontractno == null ? null : fkXscontractno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.FK_dlContractNo
     *
     * @return the value of lm_d_plan.FK_dlContractNo
     *
     * @mbggenerated
     */
    public String getFkDlcontractno() {
        return fkDlcontractno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.FK_dlContractNo
     *
     * @param fkDlcontractno the value for lm_d_plan.FK_dlContractNo
     *
     * @mbggenerated
     */
    public void setFkDlcontractno(String fkDlcontractno) {
        this.fkDlcontractno = fkDlcontractno == null ? null : fkDlcontractno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.invalid
     *
     * @return the value of lm_d_plan.invalid
     *
     * @mbggenerated
     */
    public String getInvalid() {
        return invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.invalid
     *
     * @param invalid the value for lm_d_plan.invalid
     *
     * @mbggenerated
     */
    public void setInvalid(String invalid) {
        this.invalid = invalid == null ? null : invalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.createTime
     *
     * @return the value of lm_d_plan.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.createTime
     *
     * @param createtime the value for lm_d_plan.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_plan.updateTime
     *
     * @return the value of lm_d_plan.updateTime
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_plan.updateTime
     *
     * @param updatetime the value for lm_d_plan.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }
    public String getProcurementno() {
        return procurementno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_procurementsource.procurementNo
     *
     * @param procurementno the value for lm_d_procurementsource.procurementNo
     *
     * @mbggenerated
     */
    public void setProcurementno(String procurementno) {
        this.procurementno = procurementno == null ? null : procurementno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_procurementsource.procurementName
     *
     * @return the value of lm_d_procurementsource.procurementName
     *
     * @mbggenerated
     */
    public String getProcurementname() {
        return procurementname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_procurementsource.procurementName
     *
     * @param procurementname the value for lm_d_procurementsource.procurementName
     *
     * @mbggenerated
     */
    public void setProcurementname(String procurementname) {
        this.procurementname = procurementname == null ? null : procurementname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_procurementsource.procurementWayCode
     *
     * @return the value of lm_d_procurementsource.procurementWayCode
     *
     * @mbggenerated
     */
    public String getProcurementwaycode() {
        return procurementwaycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_procurementsource.procurementWayCode
     *
     * @param procurementwaycode the value for lm_d_procurementsource.procurementWayCode
     *
     * @mbggenerated
     */
    public void setProcurementwaycode(String procurementwaycode) {
        this.procurementwaycode = procurementwaycode == null ? null : procurementwaycode.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_procurementsource.procurementCreateDate
     *
     * @return the value of lm_d_procurementsource.procurementCreateDate
     *
     * @mbggenerated
     */
    public String getProcurementcreatedate() {
        return procurementcreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_procurementsource.procurementCreateDate
     *
     * @param procurementcreatedate the value for lm_d_procurementsource.procurementCreateDate
     *
     * @mbggenerated
     */
    public void setProcurementcreatedate(String procurementcreatedate) {
        this.procurementcreatedate = procurementcreatedate == null ? null : procurementcreatedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_procurementsource.procurementAuditDate
     *
     * @return the value of lm_d_procurementsource.procurementAuditDate
     *
     * @mbggenerated
     */
    public String getProcurementauditdate() {
        return procurementauditdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_procurementsource.procurementAuditDate
     *
     * @param procurementauditdate the value for lm_d_procurementsource.procurementAuditDate
     *
     * @mbggenerated
     */
    public void setProcurementauditdate(String procurementauditdate) {
        this.procurementauditdate = procurementauditdate == null ? null : procurementauditdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_procurementsource.searchAnnouncedDate
     *
     * @return the value of lm_d_procurementsource.searchAnnouncedDate
     *
     * @mbggenerated
     */
    public String getSearchannounceddate() {
        return searchannounceddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_procurementsource.searchAnnouncedDate
     *
     * @param searchannounceddate the value for lm_d_procurementsource.searchAnnouncedDate
     *
     * @mbggenerated
     */
    public void setSearchannounceddate(String searchannounceddate) {
        this.searchannounceddate = searchannounceddate == null ? null : searchannounceddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_procurementsource.searchAuditDate
     *
     * @return the value of lm_d_procurementsource.searchAuditDate
     *
     * @mbggenerated
     */
    public String getSearchauditdate() {
        return searchauditdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_procurementsource.searchAuditDate
     *
     * @param searchauditdate the value for lm_d_procurementsource.searchAuditDate
     *
     * @mbggenerated
     */
    public void setSearchauditdate(String searchauditdate) {
        this.searchauditdate = searchauditdate == null ? null : searchauditdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_procurementsource.ExecutionWayCode
     *
     * @return the value of lm_d_procurementsource.ExecutionWayCode
     *
     * @mbggenerated
     */
    public String getExecutionwaycode() {
        return executionwaycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_procurementsource.ExecutionWayCode
     *
     * @param executionwaycode the value for lm_d_procurementsource.ExecutionWayCode
     *
     * @mbggenerated
     */
    public void setExecutionwaycode(String executionwaycode) {
        this.executionwaycode = executionwaycode == null ? null : executionwaycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_procurementsource.FK_userNo
     *
     * @return the value of lm_d_procurementsource.FK_userNo
     *
     * @mbggenerated
     */
    public String getFkUserno() {
        return fkUserno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_procurementsource.FK_userNo
     *
     * @param fkUserno the value for lm_d_procurementsource.FK_userNo
     *
     * @mbggenerated
     */
    public void setFkUserno(String fkUserno) {
        this.fkUserno = fkUserno == null ? null : fkUserno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_procurementsource.FK_deptNo
     *
     * @return the value of lm_d_procurementsource.FK_deptNo
     *
     * @mbggenerated
     */
    public String getFkDeptno() {
        return fkDeptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_procurementsource.FK_deptNo
     *
     * @param fkDeptno the value for lm_d_procurementsource.FK_deptNo
     *
     * @mbggenerated
     */
    public void setFkDeptno(String fkDeptno) {
        this.fkDeptno = fkDeptno == null ? null : fkDeptno.trim();
    }
}