package com.iboray.lms.domain.entity;

import java.util.ArrayList;
import java.util.List;

public class ReceivedExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    public ReceivedExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andReceivednoIsNull() {
            addCriterion("receivedNo is null");
            return (Criteria) this;
        }

        public Criteria andReceivednoIsNotNull() {
            addCriterion("receivedNo is not null");
            return (Criteria) this;
        }

        public Criteria andReceivednoEqualTo(String value) {
            addCriterion("receivedNo =", value, "receivedno");
            return (Criteria) this;
        }

        public Criteria andReceivednoNotEqualTo(String value) {
            addCriterion("receivedNo <>", value, "receivedno");
            return (Criteria) this;
        }

        public Criteria andReceivednoGreaterThan(String value) {
            addCriterion("receivedNo >", value, "receivedno");
            return (Criteria) this;
        }

        public Criteria andReceivednoGreaterThanOrEqualTo(String value) {
            addCriterion("receivedNo >=", value, "receivedno");
            return (Criteria) this;
        }

        public Criteria andReceivednoLessThan(String value) {
            addCriterion("receivedNo <", value, "receivedno");
            return (Criteria) this;
        }

        public Criteria andReceivednoLessThanOrEqualTo(String value) {
            addCriterion("receivedNo <=", value, "receivedno");
            return (Criteria) this;
        }

        public Criteria andReceivednoLike(String value) {
            addCriterion("receivedNo like", value, "receivedno");
            return (Criteria) this;
        }

        public Criteria andReceivednoNotLike(String value) {
            addCriterion("receivedNo not like", value, "receivedno");
            return (Criteria) this;
        }

        public Criteria andReceivednoIn(List<String> values) {
            addCriterion("receivedNo in", values, "receivedno");
            return (Criteria) this;
        }

        public Criteria andReceivednoNotIn(List<String> values) {
            addCriterion("receivedNo not in", values, "receivedno");
            return (Criteria) this;
        }

        public Criteria andReceivednoBetween(String value1, String value2) {
            addCriterion("receivedNo between", value1, value2, "receivedno");
            return (Criteria) this;
        }

        public Criteria andReceivednoNotBetween(String value1, String value2) {
            addCriterion("receivedNo not between", value1, value2, "receivedno");
            return (Criteria) this;
        }

        public Criteria andReceivedmoneyIsNull() {
            addCriterion("receivedMoney is null");
            return (Criteria) this;
        }

        public Criteria andReceivedmoneyIsNotNull() {
            addCriterion("receivedMoney is not null");
            return (Criteria) this;
        }

        public Criteria andReceivedmoneyEqualTo(Double value) {
            addCriterion("receivedMoney =", value, "receivedmoney");
            return (Criteria) this;
        }

        public Criteria andReceivedmoneyNotEqualTo(Double value) {
            addCriterion("receivedMoney <>", value, "receivedmoney");
            return (Criteria) this;
        }

        public Criteria andReceivedmoneyGreaterThan(Double value) {
            addCriterion("receivedMoney >", value, "receivedmoney");
            return (Criteria) this;
        }

        public Criteria andReceivedmoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("receivedMoney >=", value, "receivedmoney");
            return (Criteria) this;
        }

        public Criteria andReceivedmoneyLessThan(Double value) {
            addCriterion("receivedMoney <", value, "receivedmoney");
            return (Criteria) this;
        }

        public Criteria andReceivedmoneyLessThanOrEqualTo(Double value) {
            addCriterion("receivedMoney <=", value, "receivedmoney");
            return (Criteria) this;
        }

        public Criteria andReceivedmoneyIn(List<Double> values) {
            addCriterion("receivedMoney in", values, "receivedmoney");
            return (Criteria) this;
        }

        public Criteria andReceivedmoneyNotIn(List<Double> values) {
            addCriterion("receivedMoney not in", values, "receivedmoney");
            return (Criteria) this;
        }

        public Criteria andReceivedmoneyBetween(Double value1, Double value2) {
            addCriterion("receivedMoney between", value1, value2, "receivedmoney");
            return (Criteria) this;
        }

        public Criteria andReceivedmoneyNotBetween(Double value1, Double value2) {
            addCriterion("receivedMoney not between", value1, value2, "receivedmoney");
            return (Criteria) this;
        }

        public Criteria andReceivedwayIsNull() {
            addCriterion("receivedWay is null");
            return (Criteria) this;
        }

        public Criteria andReceivedwayIsNotNull() {
            addCriterion("receivedWay is not null");
            return (Criteria) this;
        }

        public Criteria andReceivedwayEqualTo(String value) {
            addCriterion("receivedWay =", value, "receivedway");
            return (Criteria) this;
        }

        public Criteria andReceivedwayNotEqualTo(String value) {
            addCriterion("receivedWay <>", value, "receivedway");
            return (Criteria) this;
        }

        public Criteria andReceivedwayGreaterThan(String value) {
            addCriterion("receivedWay >", value, "receivedway");
            return (Criteria) this;
        }

        public Criteria andReceivedwayGreaterThanOrEqualTo(String value) {
            addCriterion("receivedWay >=", value, "receivedway");
            return (Criteria) this;
        }

        public Criteria andReceivedwayLessThan(String value) {
            addCriterion("receivedWay <", value, "receivedway");
            return (Criteria) this;
        }

        public Criteria andReceivedwayLessThanOrEqualTo(String value) {
            addCriterion("receivedWay <=", value, "receivedway");
            return (Criteria) this;
        }

        public Criteria andReceivedwayLike(String value) {
            addCriterion("receivedWay like", value, "receivedway");
            return (Criteria) this;
        }

        public Criteria andReceivedwayNotLike(String value) {
            addCriterion("receivedWay not like", value, "receivedway");
            return (Criteria) this;
        }

        public Criteria andReceivedwayIn(List<String> values) {
            addCriterion("receivedWay in", values, "receivedway");
            return (Criteria) this;
        }

        public Criteria andReceivedwayNotIn(List<String> values) {
            addCriterion("receivedWay not in", values, "receivedway");
            return (Criteria) this;
        }

        public Criteria andReceivedwayBetween(String value1, String value2) {
            addCriterion("receivedWay between", value1, value2, "receivedway");
            return (Criteria) this;
        }

        public Criteria andReceivedwayNotBetween(String value1, String value2) {
            addCriterion("receivedWay not between", value1, value2, "receivedway");
            return (Criteria) this;
        }

        public Criteria andReceiveddateIsNull() {
            addCriterion("receivedDate is null");
            return (Criteria) this;
        }

        public Criteria andReceiveddateIsNotNull() {
            addCriterion("receivedDate is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveddateEqualTo(String value) {
            addCriterion("receivedDate =", value, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateNotEqualTo(String value) {
            addCriterion("receivedDate <>", value, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateGreaterThan(String value) {
            addCriterion("receivedDate >", value, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateGreaterThanOrEqualTo(String value) {
            addCriterion("receivedDate >=", value, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateLessThan(String value) {
            addCriterion("receivedDate <", value, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateLessThanOrEqualTo(String value) {
            addCriterion("receivedDate <=", value, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateLike(String value) {
            addCriterion("receivedDate like", value, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateNotLike(String value) {
            addCriterion("receivedDate not like", value, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateIn(List<String> values) {
            addCriterion("receivedDate in", values, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateNotIn(List<String> values) {
            addCriterion("receivedDate not in", values, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateBetween(String value1, String value2) {
            addCriterion("receivedDate between", value1, value2, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateNotBetween(String value1, String value2) {
            addCriterion("receivedDate not between", value1, value2, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoIsNull() {
            addCriterion("FK_xsContractNo is null");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoIsNotNull() {
            addCriterion("FK_xsContractNo is not null");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoEqualTo(String value) {
            addCriterion("FK_xsContractNo =", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoNotEqualTo(String value) {
            addCriterion("FK_xsContractNo <>", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoGreaterThan(String value) {
            addCriterion("FK_xsContractNo >", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoGreaterThanOrEqualTo(String value) {
            addCriterion("FK_xsContractNo >=", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoLessThan(String value) {
            addCriterion("FK_xsContractNo <", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoLessThanOrEqualTo(String value) {
            addCriterion("FK_xsContractNo <=", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoLike(String value) {
            addCriterion("FK_xsContractNo like", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoNotLike(String value) {
            addCriterion("FK_xsContractNo not like", value, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoIn(List<String> values) {
            addCriterion("FK_xsContractNo in", values, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoNotIn(List<String> values) {
            addCriterion("FK_xsContractNo not in", values, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoBetween(String value1, String value2) {
            addCriterion("FK_xsContractNo between", value1, value2, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkXscontractnoNotBetween(String value1, String value2) {
            addCriterion("FK_xsContractNo not between", value1, value2, "fkXscontractno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIsNull() {
            addCriterion("FK_userNo is null");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIsNotNull() {
            addCriterion("FK_userNo is not null");
            return (Criteria) this;
        }

        public Criteria andFkUsernoEqualTo(String value) {
            addCriterion("FK_userNo =", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotEqualTo(String value) {
            addCriterion("FK_userNo <>", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoGreaterThan(String value) {
            addCriterion("FK_userNo >", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoGreaterThanOrEqualTo(String value) {
            addCriterion("FK_userNo >=", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLessThan(String value) {
            addCriterion("FK_userNo <", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLessThanOrEqualTo(String value) {
            addCriterion("FK_userNo <=", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoLike(String value) {
            addCriterion("FK_userNo like", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotLike(String value) {
            addCriterion("FK_userNo not like", value, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoIn(List<String> values) {
            addCriterion("FK_userNo in", values, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotIn(List<String> values) {
            addCriterion("FK_userNo not in", values, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoBetween(String value1, String value2) {
            addCriterion("FK_userNo between", value1, value2, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andFkUsernoNotBetween(String value1, String value2) {
            addCriterion("FK_userNo not between", value1, value2, "fkUserno");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNull() {
            addCriterion("invalid is null");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNotNull() {
            addCriterion("invalid is not null");
            return (Criteria) this;
        }

        public Criteria andInvalidEqualTo(String value) {
            addCriterion("invalid =", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotEqualTo(String value) {
            addCriterion("invalid <>", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThan(String value) {
            addCriterion("invalid >", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThanOrEqualTo(String value) {
            addCriterion("invalid >=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThan(String value) {
            addCriterion("invalid <", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThanOrEqualTo(String value) {
            addCriterion("invalid <=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLike(String value) {
            addCriterion("invalid like", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotLike(String value) {
            addCriterion("invalid not like", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidIn(List<String> values) {
            addCriterion("invalid in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotIn(List<String> values) {
            addCriterion("invalid not in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidBetween(String value1, String value2) {
            addCriterion("invalid between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotBetween(String value1, String value2) {
            addCriterion("invalid not between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("createTime like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("createTime not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(String value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(String value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(String value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(String value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(String value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLike(String value) {
            addCriterion("updateTime like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotLike(String value) {
            addCriterion("updateTime not like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<String> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<String> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(String value1, String value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(String value1, String value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_received
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_d_received
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}