package com.iboray.lms.domain.entity;

public class Received {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_received.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_received.receivedNo
     *
     * @mbggenerated
     */
    private String receivedno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_received.receivedMoney
     *
     * @mbggenerated
     */
    private Double receivedmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_received.receivedWay
     *
     * @mbggenerated
     */
    private String receivedway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_received.receivedDate
     *
     * @mbggenerated
     */
    private String receiveddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_received.FK_xsContractNo
     *
     * @mbggenerated
     */
    private String fkXscontractno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_received.FK_userNo
     *
     * @mbggenerated
     */
    private String fkUserno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_received.invalid
     *
     * @mbggenerated
     */
    private String invalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_received.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_received.updateTime
     *
     * @mbggenerated
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_received.id
     *
     * @return the value of lm_d_received.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_received.id
     *
     * @param id the value for lm_d_received.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_received.receivedNo
     *
     * @return the value of lm_d_received.receivedNo
     *
     * @mbggenerated
     */
    public String getReceivedno() {
        return receivedno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_received.receivedNo
     *
     * @param receivedno the value for lm_d_received.receivedNo
     *
     * @mbggenerated
     */
    public void setReceivedno(String receivedno) {
        this.receivedno = receivedno == null ? null : receivedno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_received.receivedMoney
     *
     * @return the value of lm_d_received.receivedMoney
     *
     * @mbggenerated
     */
    public Double getReceivedmoney() {
        return receivedmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_received.receivedMoney
     *
     * @param receivedmoney the value for lm_d_received.receivedMoney
     *
     * @mbggenerated
     */
    public void setReceivedmoney(Double receivedmoney) {
        this.receivedmoney = receivedmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_received.receivedWay
     *
     * @return the value of lm_d_received.receivedWay
     *
     * @mbggenerated
     */
    public String getReceivedway() {
        return receivedway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_received.receivedWay
     *
     * @param receivedway the value for lm_d_received.receivedWay
     *
     * @mbggenerated
     */
    public void setReceivedway(String receivedway) {
        this.receivedway = receivedway == null ? null : receivedway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_received.receivedDate
     *
     * @return the value of lm_d_received.receivedDate
     *
     * @mbggenerated
     */
    public String getReceiveddate() {
        return receiveddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_received.receivedDate
     *
     * @param receiveddate the value for lm_d_received.receivedDate
     *
     * @mbggenerated
     */
    public void setReceiveddate(String receiveddate) {
        this.receiveddate = receiveddate == null ? null : receiveddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_received.FK_xsContractNo
     *
     * @return the value of lm_d_received.FK_xsContractNo
     *
     * @mbggenerated
     */
    public String getFkXscontractno() {
        return fkXscontractno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_received.FK_xsContractNo
     *
     * @param fkXscontractno the value for lm_d_received.FK_xsContractNo
     *
     * @mbggenerated
     */
    public void setFkXscontractno(String fkXscontractno) {
        this.fkXscontractno = fkXscontractno == null ? null : fkXscontractno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_received.FK_userNo
     *
     * @return the value of lm_d_received.FK_userNo
     *
     * @mbggenerated
     */
    public String getFkUserno() {
        return fkUserno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_received.FK_userNo
     *
     * @param fkUserno the value for lm_d_received.FK_userNo
     *
     * @mbggenerated
     */
    public void setFkUserno(String fkUserno) {
        this.fkUserno = fkUserno == null ? null : fkUserno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_received.invalid
     *
     * @return the value of lm_d_received.invalid
     *
     * @mbggenerated
     */
    public String getInvalid() {
        return invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_received.invalid
     *
     * @param invalid the value for lm_d_received.invalid
     *
     * @mbggenerated
     */
    public void setInvalid(String invalid) {
        this.invalid = invalid == null ? null : invalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_received.createTime
     *
     * @return the value of lm_d_received.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_received.createTime
     *
     * @param createtime the value for lm_d_received.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_received.updateTime
     *
     * @return the value of lm_d_received.updateTime
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_received.updateTime
     *
     * @param updatetime the value for lm_d_received.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }
}