package com.iboray.lms.domain.entity;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_role.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_role.roleNo
     *
     * @mbggenerated
     */
    private String roleno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_role.roleName
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_role.roleValue
     *
     * @mbggenerated
     */
    private String rolevalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_role.invalid
     *
     * @mbggenerated
     */
    private String invalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_role.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_role.updateTime
     *
     * @mbggenerated
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_role.id
     *
     * @return the value of lm_a_role.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_role.id
     *
     * @param id the value for lm_a_role.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_role.roleNo
     *
     * @return the value of lm_a_role.roleNo
     *
     * @mbggenerated
     */
    public String getRoleno() {
        return roleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_role.roleNo
     *
     * @param roleno the value for lm_a_role.roleNo
     *
     * @mbggenerated
     */
    public void setRoleno(String roleno) {
        this.roleno = roleno == null ? null : roleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_role.roleName
     *
     * @return the value of lm_a_role.roleName
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_role.roleName
     *
     * @param rolename the value for lm_a_role.roleName
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_role.roleValue
     *
     * @return the value of lm_a_role.roleValue
     *
     * @mbggenerated
     */
    public String getRolevalue() {
        return rolevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_role.roleValue
     *
     * @param rolevalue the value for lm_a_role.roleValue
     *
     * @mbggenerated
     */
    public void setRolevalue(String rolevalue) {
        this.rolevalue = rolevalue == null ? null : rolevalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_role.invalid
     *
     * @return the value of lm_a_role.invalid
     *
     * @mbggenerated
     */
    public String getInvalid() {
        return invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_role.invalid
     *
     * @param invalid the value for lm_a_role.invalid
     *
     * @mbggenerated
     */
    public void setInvalid(String invalid) {
        this.invalid = invalid == null ? null : invalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_role.createTime
     *
     * @return the value of lm_a_role.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_role.createTime
     *
     * @param createtime the value for lm_a_role.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_role.updateTime
     *
     * @return the value of lm_a_role.updateTime
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_role.updateTime
     *
     * @param updatetime the value for lm_a_role.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }
}