package com.iboray.lms.domain.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_user.userNo
     *
     * @mbggenerated
     */
    private String userno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_user.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_user.userType
     *
     * @mbggenerated
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_user.personName
     *
     * @mbggenerated
     */
    private String personname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_user.FK_deptNo
     *
     * @mbggenerated
     */
    private String fkDeptno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_user.dataRole
     *
     * @mbggenerated
     */
    private String datarole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_user.invalid
     *
     * @mbggenerated
     */
    private String invalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_user.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_user.updateTime
     *
     * @mbggenerated
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_user.id
     *
     * @return the value of lm_a_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_user.id
     *
     * @param id the value for lm_a_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_user.userNo
     *
     * @return the value of lm_a_user.userNo
     *
     * @mbggenerated
     */
    public String getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_user.userNo
     *
     * @param userno the value for lm_a_user.userNo
     *
     * @mbggenerated
     */
    public void setUserno(String userno) {
        this.userno = userno == null ? null : userno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_user.userName
     *
     * @return the value of lm_a_user.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_user.userName
     *
     * @param username the value for lm_a_user.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_user.password
     *
     * @return the value of lm_a_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_user.password
     *
     * @param password the value for lm_a_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_user.userType
     *
     * @return the value of lm_a_user.userType
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_user.userType
     *
     * @param usertype the value for lm_a_user.userType
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_user.personName
     *
     * @return the value of lm_a_user.personName
     *
     * @mbggenerated
     */
    public String getPersonname() {
        return personname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_user.personName
     *
     * @param personname the value for lm_a_user.personName
     *
     * @mbggenerated
     */
    public void setPersonname(String personname) {
        this.personname = personname == null ? null : personname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_user.FK_deptNo
     *
     * @return the value of lm_a_user.FK_deptNo
     *
     * @mbggenerated
     */
    public String getFkDeptno() {
        return fkDeptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_user.FK_deptNo
     *
     * @param fkDeptno the value for lm_a_user.FK_deptNo
     *
     * @mbggenerated
     */
    public void setFkDeptno(String fkDeptno) {
        this.fkDeptno = fkDeptno == null ? null : fkDeptno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_user.dataRole
     *
     * @return the value of lm_a_user.dataRole
     *
     * @mbggenerated
     */
    public String getDatarole() {
        return datarole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_user.dataRole
     *
     * @param datarole the value for lm_a_user.dataRole
     *
     * @mbggenerated
     */
    public void setDatarole(String datarole) {
        this.datarole = datarole == null ? null : datarole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_user.invalid
     *
     * @return the value of lm_a_user.invalid
     *
     * @mbggenerated
     */
    public String getInvalid() {
        return invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_user.invalid
     *
     * @param invalid the value for lm_a_user.invalid
     *
     * @mbggenerated
     */
    public void setInvalid(String invalid) {
        this.invalid = invalid == null ? null : invalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_user.createTime
     *
     * @return the value of lm_a_user.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_user.createTime
     *
     * @param createtime the value for lm_a_user.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_user.updateTime
     *
     * @return the value of lm_a_user.updateTime
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_user.updateTime
     *
     * @param updatetime the value for lm_a_user.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }
}