package com.iboray.lms.domain.entity;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_userrole.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_userrole.FK_userNo
     *
     * @mbggenerated
     */
    private String fkUserno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_userrole.FK_roleNo
     *
     * @mbggenerated
     */
    private String fkRoleno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_userrole.invalid
     *
     * @mbggenerated
     */
    private String invalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_userrole.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_a_userrole.updateTime
     *
     * @mbggenerated
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_userrole.id
     *
     * @return the value of lm_a_userrole.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_userrole.id
     *
     * @param id the value for lm_a_userrole.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_userrole.FK_userNo
     *
     * @return the value of lm_a_userrole.FK_userNo
     *
     * @mbggenerated
     */
    public String getFkUserno() {
        return fkUserno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_userrole.FK_userNo
     *
     * @param fkUserno the value for lm_a_userrole.FK_userNo
     *
     * @mbggenerated
     */
    public void setFkUserno(String fkUserno) {
        this.fkUserno = fkUserno == null ? null : fkUserno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_userrole.FK_roleNo
     *
     * @return the value of lm_a_userrole.FK_roleNo
     *
     * @mbggenerated
     */
    public String getFkRoleno() {
        return fkRoleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_userrole.FK_roleNo
     *
     * @param fkRoleno the value for lm_a_userrole.FK_roleNo
     *
     * @mbggenerated
     */
    public void setFkRoleno(String fkRoleno) {
        this.fkRoleno = fkRoleno == null ? null : fkRoleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_userrole.invalid
     *
     * @return the value of lm_a_userrole.invalid
     *
     * @mbggenerated
     */
    public String getInvalid() {
        return invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_userrole.invalid
     *
     * @param invalid the value for lm_a_userrole.invalid
     *
     * @mbggenerated
     */
    public void setInvalid(String invalid) {
        this.invalid = invalid == null ? null : invalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_userrole.createTime
     *
     * @return the value of lm_a_userrole.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_userrole.createTime
     *
     * @param createtime the value for lm_a_userrole.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_a_userrole.updateTime
     *
     * @return the value of lm_a_userrole.updateTime
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_a_userrole.updateTime
     *
     * @param updatetime the value for lm_a_userrole.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }
}