package com.iboray.lms.domain.entity;

public class Xscontract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.xsContractNo
     *
     * @mbggenerated
     */
    private String xscontractno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.xsContractName
     *
     * @mbggenerated
     */
    private String xscontractname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.xsContractNum
     *
     * @mbggenerated
     */
    private String xscontractnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.signingDate
     *
     * @mbggenerated
     */
    private String signingdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.totalMoney
     *
     * @mbggenerated
     */
    private Double totalmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.qualityMoney
     *
     * @mbggenerated
     */
    private Double qualitymoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.qualityDate
     *
     * @mbggenerated
     */
    private String qualitydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.signComp
     *
     * @mbggenerated
     */
    private String signcomp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.salesRate
     *
     * @mbggenerated
     */
    private Double salesrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.FK_userNo
     *
     * @mbggenerated
     */
    private String fkUserno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.FK_cgContractNo
     *
     * @mbggenerated
     */
    private String fkCgcontractno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.FK_deptNo
     *
     * @mbggenerated
     */
    private String fkDeptno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.FK_usecompNo
     *
     * @mbggenerated
     */
    private String fkUsecompno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.invalid
     *
     * @mbggenerated
     */
    private String invalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_d_xscontract.updateTime
     *
     * @mbggenerated
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.id
     *
     * @return the value of lm_d_xscontract.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.id
     *
     * @param id the value for lm_d_xscontract.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.xsContractNo
     *
     * @return the value of lm_d_xscontract.xsContractNo
     *
     * @mbggenerated
     */
    public String getXscontractno() {
        return xscontractno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.xsContractNo
     *
     * @param xscontractno the value for lm_d_xscontract.xsContractNo
     *
     * @mbggenerated
     */
    public void setXscontractno(String xscontractno) {
        this.xscontractno = xscontractno == null ? null : xscontractno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.xsContractName
     *
     * @return the value of lm_d_xscontract.xsContractName
     *
     * @mbggenerated
     */
    public String getXscontractname() {
        return xscontractname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.xsContractName
     *
     * @param xscontractname the value for lm_d_xscontract.xsContractName
     *
     * @mbggenerated
     */
    public void setXscontractname(String xscontractname) {
        this.xscontractname = xscontractname == null ? null : xscontractname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.xsContractNum
     *
     * @return the value of lm_d_xscontract.xsContractNum
     *
     * @mbggenerated
     */
    public String getXscontractnum() {
        return xscontractnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.xsContractNum
     *
     * @param xscontractnum the value for lm_d_xscontract.xsContractNum
     *
     * @mbggenerated
     */
    public void setXscontractnum(String xscontractnum) {
        this.xscontractnum = xscontractnum == null ? null : xscontractnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.signingDate
     *
     * @return the value of lm_d_xscontract.signingDate
     *
     * @mbggenerated
     */
    public String getSigningdate() {
        return signingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.signingDate
     *
     * @param signingdate the value for lm_d_xscontract.signingDate
     *
     * @mbggenerated
     */
    public void setSigningdate(String signingdate) {
        this.signingdate = signingdate == null ? null : signingdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.totalMoney
     *
     * @return the value of lm_d_xscontract.totalMoney
     *
     * @mbggenerated
     */
    public Double getTotalmoney() {
        return totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.totalMoney
     *
     * @param totalmoney the value for lm_d_xscontract.totalMoney
     *
     * @mbggenerated
     */
    public void setTotalmoney(Double totalmoney) {
        this.totalmoney = totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.qualityMoney
     *
     * @return the value of lm_d_xscontract.qualityMoney
     *
     * @mbggenerated
     */
    public Double getQualitymoney() {
        return qualitymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.qualityMoney
     *
     * @param qualitymoney the value for lm_d_xscontract.qualityMoney
     *
     * @mbggenerated
     */
    public void setQualitymoney(Double qualitymoney) {
        this.qualitymoney = qualitymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.qualityDate
     *
     * @return the value of lm_d_xscontract.qualityDate
     *
     * @mbggenerated
     */
    public String getQualitydate() {
        return qualitydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.qualityDate
     *
     * @param qualitydate the value for lm_d_xscontract.qualityDate
     *
     * @mbggenerated
     */
    public void setQualitydate(String qualitydate) {
        this.qualitydate = qualitydate == null ? null : qualitydate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.signComp
     *
     * @return the value of lm_d_xscontract.signComp
     *
     * @mbggenerated
     */
    public String getSigncomp() {
        return signcomp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.signComp
     *
     * @param signcomp the value for lm_d_xscontract.signComp
     *
     * @mbggenerated
     */
    public void setSigncomp(String signcomp) {
        this.signcomp = signcomp == null ? null : signcomp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.salesRate
     *
     * @return the value of lm_d_xscontract.salesRate
     *
     * @mbggenerated
     */
    public Double getSalesrate() {
        return salesrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.salesRate
     *
     * @param salesrate the value for lm_d_xscontract.salesRate
     *
     * @mbggenerated
     */
    public void setSalesrate(Double salesrate) {
        this.salesrate = salesrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.FK_userNo
     *
     * @return the value of lm_d_xscontract.FK_userNo
     *
     * @mbggenerated
     */
    public String getFkUserno() {
        return fkUserno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.FK_userNo
     *
     * @param fkUserno the value for lm_d_xscontract.FK_userNo
     *
     * @mbggenerated
     */
    public void setFkUserno(String fkUserno) {
        this.fkUserno = fkUserno == null ? null : fkUserno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.FK_cgContractNo
     *
     * @return the value of lm_d_xscontract.FK_cgContractNo
     *
     * @mbggenerated
     */
    public String getFkCgcontractno() {
        return fkCgcontractno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.FK_cgContractNo
     *
     * @param fkCgcontractno the value for lm_d_xscontract.FK_cgContractNo
     *
     * @mbggenerated
     */
    public void setFkCgcontractno(String fkCgcontractno) {
        this.fkCgcontractno = fkCgcontractno == null ? null : fkCgcontractno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.FK_deptNo
     *
     * @return the value of lm_d_xscontract.FK_deptNo
     *
     * @mbggenerated
     */
    public String getFkDeptno() {
        return fkDeptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.FK_deptNo
     *
     * @param fkDeptno the value for lm_d_xscontract.FK_deptNo
     *
     * @mbggenerated
     */
    public void setFkDeptno(String fkDeptno) {
        this.fkDeptno = fkDeptno == null ? null : fkDeptno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.FK_usecompNo
     *
     * @return the value of lm_d_xscontract.FK_usecompNo
     *
     * @mbggenerated
     */
    public String getFkUsecompno() {
        return fkUsecompno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.FK_usecompNo
     *
     * @param fkUsecompno the value for lm_d_xscontract.FK_usecompNo
     *
     * @mbggenerated
     */
    public void setFkUsecompno(String fkUsecompno) {
        this.fkUsecompno = fkUsecompno == null ? null : fkUsecompno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.invalid
     *
     * @return the value of lm_d_xscontract.invalid
     *
     * @mbggenerated
     */
    public String getInvalid() {
        return invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.invalid
     *
     * @param invalid the value for lm_d_xscontract.invalid
     *
     * @mbggenerated
     */
    public void setInvalid(String invalid) {
        this.invalid = invalid == null ? null : invalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.createTime
     *
     * @return the value of lm_d_xscontract.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.createTime
     *
     * @param createtime the value for lm_d_xscontract.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_d_xscontract.updateTime
     *
     * @return the value of lm_d_xscontract.updateTime
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_d_xscontract.updateTime
     *
     * @param updatetime the value for lm_d_xscontract.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }
}